using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.ObjectPool;

[Generator]
public sealed class ObjectPoolGenerator : IIncrementalGenerator
{
    private const string AttributeName = "PatternKit.Generators.ObjectPool.GenerateObjectPoolAttribute";

    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKOP001",
        "Object Pool host must be partial",
        "Type '{0}' is marked with [GenerateObjectPool] but is not declared as partial",
        "PatternKit.Generators.ObjectPool",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidConfiguration = new(
        "PKOP002",
        "Object Pool configuration is invalid",
        "Object Pool '{0}' must have a non-empty FactoryMethodName and MaxRetained greater than or equal to -1",
        "PatternKit.Generators.ObjectPool",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor RequiresParameterlessConstructor = new(
        "PKOP003",
        "Object Pool item requires a public parameterless constructor",
        "Object Pool item type '{0}' must expose a public parameterless constructor or be a value type",
        "PatternKit.Generators.ObjectPool",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static attribute =>
                attribute.AttributeClass?.ToDisplayString() == AttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var itemType = attribute.ConstructorArguments.Length >= 1 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (itemType is null || itemType.TypeKind == TypeKind.Error)
            return;

        var factoryMethodName = GetNamedString(attribute, "FactoryMethodName") ?? "Create";
        var maxRetained = GetNamedInt(attribute, "MaxRetained") ?? -1;
        var resetMethodName = GetNamedString(attribute, "ResetMethodName");
        if (string.IsNullOrWhiteSpace(factoryMethodName) || maxRetained < -1)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidConfiguration, node.Identifier.GetLocation(), type.Name));
            return;
        }

        if (!CanCreate(itemType))
        {
            context.ReportDiagnostic(Diagnostic.Create(RequiresParameterlessConstructor, node.Identifier.GetLocation(), itemType.ToDisplayString()));
            return;
        }

        context.AddSource($"{type.Name}.ObjectPool.g.cs", SourceText.From(
            GenerateSource(type, itemType, factoryMethodName, maxRetained, resetMethodName),
            Encoding.UTF8));
    }

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol itemType, string factoryMethodName, int maxRetained, string? resetMethodName)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var itemTypeName = itemType.ToDisplayString(TypeFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        var indent = string.Empty;
        foreach (var containingType in GetContainingTypes(type))
        {
            AppendTypeDeclaration(sb, containingType, indent);
            sb.Append(indent).AppendLine("{");
            indent += "    ";
        }

        AppendTypeDeclaration(sb, type, indent);
        sb.Append(indent).AppendLine("{");
        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";
        sb.Append(memberIndent).Append("public static global::PatternKit.Creational.ObjectPool.ObjectPool<").Append(itemTypeName).Append("> ").Append(factoryMethodName).AppendLine("()");
        sb.Append(memberIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("var builder = global::PatternKit.Creational.ObjectPool.ObjectPool<").Append(itemTypeName).Append(">.Create()");
        sb.AppendLine();
        sb.Append(bodyIndent).Append("    .WithFactory(static () => new ").Append(itemTypeName).AppendLine("());");
        if (!string.IsNullOrWhiteSpace(resetMethodName))
            sb.Append(bodyIndent).Append("builder.OnReturn(static item => item.").Append(resetMethodName).AppendLine("());");
        if (maxRetained >= 0)
            sb.Append(bodyIndent).Append("builder.WithMaxRetained(").Append(maxRetained).AppendLine(");");
        sb.Append(bodyIndent).AppendLine("return builder.Build();");
        sb.Append(memberIndent).AppendLine("}");
        sb.Append(indent).AppendLine("}");
        while (indent.Length > 0)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.Append(indent).AppendLine("}");
        }

        return sb.ToString();
    }

    private static bool CanCreate(INamedTypeSymbol itemType)
        => itemType.IsValueType
        || itemType.InstanceConstructors.Any(static constructor =>
            constructor.Parameters.Length == 0 && constructor.DeclaredAccessibility == Accessibility.Public);

    private static IReadOnlyList<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol type)
    {
        var stack = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
            stack.Push(current);
        return stack.ToArray();
    }

    private static void AppendTypeDeclaration(StringBuilder sb, INamedTypeSymbol type, string indent)
    {
        sb.Append(indent).Append(GetAccessibility(type.DeclaredAccessibility)).Append(' ');
        if (type.IsStatic)
            sb.Append("static ");
        else if (type.IsAbstract && type.TypeKind == TypeKind.Class)
            sb.Append("abstract ");
        else if (type.IsSealed && type.TypeKind == TypeKind.Class)
            sb.Append("sealed ");
        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static int? GetNamedInt(AttributeData attribute, string name)
    {
        var value = attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value;
        return value.Value is int integer ? integer : null;
    }

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };
}
