using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PatternKit.Generators.Iterator;

[Generator]
public sealed class IteratorGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                              SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly DiagnosticDescriptor MustBePartial = new("PKIT001", "Iterator type must be partial", "Type '{0}' is marked with [Iterator] but is not declared as partial", "PatternKit.Generators.Iterator", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingStep = new("PKIT002", "Iterator step missing", "No [IteratorStep] method found for iterator type '{0}'", "PatternKit.Generators.Iterator", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MultipleSteps = new("PKIT003", "Multiple iterator steps", "Multiple [IteratorStep] methods found for iterator type '{0}'", "PatternKit.Generators.Iterator", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidStep = new("PKIT004", "Iterator step signature invalid", "Iterator step '{0}' must return bool and accept one out item parameter", "PatternKit.Generators.Iterator", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var iterators = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Iterator.IteratorAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => ctx);

        context.RegisterSourceOutput(iterators, static (spc, ctx) =>
        {
            if (ctx.TargetSymbol is INamedTypeSymbol type)
            {
                var attr = ctx.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Iterator.IteratorAttribute");
                if (attr is not null) Generate(spc, type, attr, ctx.TargetNode);
            }
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, AttributeData attr, SyntaxNode node)
    {
        if (!IsPartial(node))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.GetLocation(), type.Name));
            return;
        }

        var steps = type.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Iterator.IteratorStepAttribute"))
            .ToArray();
        if (steps.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingStep, node.GetLocation(), type.Name));
            return;
        }
        if (steps.Length > 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MultipleSteps, node.GetLocation(), type.Name));
            return;
        }
        var step = steps[0];
        if (step.ReturnType.SpecialType != SpecialType.System_Boolean || step.Parameters.Length != 1 || step.Parameters[0].RefKind != RefKind.Out)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidStep, node.GetLocation(), step.Name));
            return;
        }

        var generateTry = GetBool(attr, nameof(IteratorAttribute.GenerateTryMoveNext), true);
        var generateEnumerator = GetBool(attr, nameof(IteratorAttribute.GenerateEnumerator), true);
        context.AddSource($"{type.Name}.Iterator.g.cs", Render(type, step, step.Parameters[0].Type, generateTry, generateEnumerator));
    }

    private static string Render(INamedTypeSymbol type, IMethodSymbol step, ITypeSymbol itemType, bool generateTry, bool generateEnumerator)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var item = itemType.ToDisplayString(TypeFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append("public partial ").Append(GetKind(type)).Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public ").Append(item).Append(" Current { get; private set; }").AppendLine();
        if (generateTry)
        {
            sb.AppendLine();
            sb.Append("    public bool TryMoveNext(out ").Append(item).Append(" item)").AppendLine();
            sb.AppendLine("    {");
            sb.Append("        if (").Append(step.Name).Append("(out item))").AppendLine();
            sb.AppendLine("        {");
            sb.AppendLine("            Current = item;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        Current = default!;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
        }
        if (generateEnumerator)
        {
            sb.AppendLine();
            sb.AppendLine("    public Enumerator GetEnumerator() => new(this);");
            sb.AppendLine();
            sb.Append("    public struct Enumerator : global::System.Collections.Generic.IEnumerator<").Append(item).Append(">").AppendLine();
            sb.AppendLine("    {");
            sb.Append("        private ").Append(type.ToDisplayString(TypeFormat)).Append(" _iterator;").AppendLine();
            sb.Append("        private ").Append(item).Append(" _current;").AppendLine();
            sb.AppendLine();
            sb.Append("        internal Enumerator(").Append(type.ToDisplayString(TypeFormat)).Append(" iterator)").AppendLine();
            sb.AppendLine("        {");
            sb.AppendLine("            _iterator = iterator;");
            sb.AppendLine("            _current = default!;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.Append("        public ").Append(item).Append(" Current => _current;").AppendLine();
            sb.AppendLine("        object? System.Collections.IEnumerator.Current => Current;");
            sb.AppendLine("        public bool MoveNext() => _iterator.TryMoveNext(out _current);");
            sb.AppendLine("        public void Reset() => throw new global::System.NotSupportedException();");
            sb.AppendLine("        public void Dispose() { }");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsPartial(SyntaxNode node) => node is TypeDeclarationSyntax type && type.Modifiers.Any(SyntaxKind.PartialKeyword);
    private static bool GetBool(AttributeData attr, string name, bool fallback) => attr.NamedArguments.FirstOrDefault(a => a.Key == name).Value.Value is bool value ? value : fallback;
    private static string GetKind(INamedTypeSymbol type) => type.TypeKind == TypeKind.Struct ? (type.IsRecord ? "record struct" : "struct") : (type.IsRecord ? "record class" : "class");
}
