using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class DeadLetterChannelGenerator : IIncrementalGenerator
{
    private const string GenerateAttributeName = "PatternKit.Generators.Messaging.GenerateDeadLetterChannelAttribute";
    private const string StoreFactoryAttributeName = "PatternKit.Generators.Messaging.DeadLetterStoreFactoryAttribute";

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKDL001",
        "Dead-letter channel host must be partial",
        "Type '{0}' is marked with [GenerateDeadLetterChannel] but is not declared as partial",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor MissingStoreFactory = new(
        "PKDL002",
        "Dead-letter store factory is missing",
        "Dead-letter channel '{0}' must declare exactly one [DeadLetterStoreFactory] method",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidStoreFactory = new(
        "PKDL003",
        "Dead-letter store factory signature is invalid",
        "Dead-letter store factory '{0}' must be static, parameterless, and return IDeadLetterStore<TPayload>",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateAttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == GenerateAttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length >= 1 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (payloadType is null)
            return;

        var factories = type.GetMembers().OfType<IMethodSymbol>()
            .Where(static method => method.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == StoreFactoryAttributeName))
            .ToArray();
        if (factories.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingStoreFactory, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var factory = factories[0];
        if (!IsStoreFactory(factory, payloadType))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidStoreFactory, factory.Locations.FirstOrDefault(), factory.Name));
            return;
        }

        context.AddSource($"{type.Name}.DeadLetterChannel.g.cs", SourceText.From(
            GenerateSource(
                type,
                payloadType,
                factory.Name,
                GetNamedString(attribute, "FactoryName") ?? "Create",
                GetNamedString(attribute, "ChannelName") ?? "dead-letter-channel",
                GetNamedString(attribute, "Source") ?? "application",
                GetNamedString(attribute, "IdPrefix") ?? "dead",
                GetNamedBool(attribute, "IncludeExceptionDetails") ?? true),
            Encoding.UTF8));
    }

    private static string GenerateSource(
        INamedTypeSymbol type,
        INamedTypeSymbol payloadType,
        string storeFactory,
        string factoryName,
        string channelName,
        string source,
        string idPrefix,
        bool includeExceptionDetails)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var payloadName = payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        var containingTypes = GetContainingTypes(type);
        var indentLevel = 0;
        foreach (var containingType in containingTypes)
        {
            AppendTypeDeclaration(sb, containingType, indentLevel);
            sb.AppendLine();
            sb.AppendLine(new string(' ', indentLevel * 4) + "{");
            indentLevel++;
        }

        AppendTypeDeclaration(sb, type, indentLevel);
        sb.AppendLine();
        var indent = new string(' ', indentLevel * 4);
        sb.AppendLine(indent + "{");
        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";
        sb.Append(memberIndent).Append("public static global::PatternKit.Messaging.Reliability.DeadLetterChannel<")
            .Append(payloadName).Append("> ").Append(factoryName).AppendLine("()");
        sb.Append(bodyIndent).Append("=> global::PatternKit.Messaging.Reliability.DeadLetterChannel<")
            .Append(payloadName).Append(">.Create(\"").Append(Escape(channelName)).AppendLine("\")");
        sb.Append(bodyIndent).Append("    .FromSource(\"").Append(Escape(source)).AppendLine("\")");
        sb.Append(bodyIndent).Append("    .UseStore(").Append(storeFactory).AppendLine("())");
        sb.Append(bodyIndent).Append("    .UseIds(static (message, _, _) => \"")
            .Append(Escape(idPrefix))
            .Append(":\" + (message.Headers.MessageId ?? global::System.Guid.NewGuid().ToString(\"N\")))")
            .AppendLine();
        sb.Append(bodyIndent).Append("    .IncludeExceptionDetails(").Append(includeExceptionDetails ? "true" : "false").AppendLine(")");
        sb.Append(bodyIndent).AppendLine("    .Build();");
        sb.AppendLine(indent + "}");
        for (var i = containingTypes.Length - 1; i >= 0; i--)
        {
            sb.AppendLine(new string(' ', i * 4) + "}");
        }

        return sb.ToString();
    }

    private static INamedTypeSymbol[] GetContainingTypes(INamedTypeSymbol type)
    {
        var containingTypes = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
        {
            containingTypes.Push(current);
        }

        return containingTypes.ToArray();
    }

    private static void AppendTypeDeclaration(StringBuilder sb, INamedTypeSymbol type, int indentLevel)
    {
        sb.Append(new string(' ', indentLevel * 4));
        sb.Append(GetAccessibility(type.DeclaredAccessibility)).Append(' ');
        if (type.IsStatic)
            sb.Append("static ");
        else if (type.IsAbstract && type.TypeKind == TypeKind.Class)
            sb.Append("abstract ");
        else if (type.IsSealed && type.TypeKind == TypeKind.Class)
            sb.Append("sealed ");
        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name);
    }

    private static bool IsStoreFactory(IMethodSymbol method, ITypeSymbol payloadType)
        => method.IsStatic
        && !method.IsGenericMethod
        && method.Parameters.Length == 0
        && method.ReturnType is INamedTypeSymbol named
        && named.ConstructedFrom.ToDisplayString() == "PatternKit.Messaging.Reliability.IDeadLetterStore<TPayload>"
        && SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], payloadType);

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static bool? GetNamedBool(AttributeData attribute, string name)
    {
        var value = attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value;
        return value.Value is bool boolean ? boolean : null;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };
}
