using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class DurableSubscriberGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("PKDS001", "Durable subscriber type must be partial", "Type '{0}' is marked with [GenerateDurableSubscriber] but is not declared as partial", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingHandler = new("PKDS002", "Durable subscriber handler is missing", "Type '{0}' must declare at least one [DurableSubscriberHandler] method", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidHandler = new("PKDS003", "Durable subscriber handler signature is invalid", "Handler '{0}' must be static and return DurableSubscriberHandlerResult with StoredMessage<TPayload> and MessageContext parameters", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GenerateDurableSubscriberAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GenerateDurableSubscriberAttribute");
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (payloadType is null)
            return;

        var handlers = type.GetMembers().OfType<IMethodSymbol>().Where(static method =>
            method.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.DurableSubscriberHandlerAttribute")).ToArray();
        if (handlers.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingHandler, node.Identifier.GetLocation(), type.Name));
            return;
        }

        foreach (var handler in handlers)
        {
            if (!IsHandler(handler, payloadType))
            {
                context.ReportDiagnostic(Diagnostic.Create(InvalidHandler, handler.Locations.FirstOrDefault(), handler.Name));
                return;
            }
        }

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var subscriberName = GetNamedString(attribute, "SubscriberName") ?? "durable-subscriber";
        context.AddSource($"{type.Name}.DurableSubscriber.g.cs", SourceText.From(GenerateSource(type, payloadType, handlers, factoryName, subscriberName), Encoding.UTF8));
    }

    private static bool IsHandler(IMethodSymbol method, INamedTypeSymbol payloadType)
        => method.IsStatic &&
           method.ReturnType.ToDisplayString() == "PatternKit.Messaging.Consumers.DurableSubscriberHandlerResult" &&
           method.Parameters.Length == 2 &&
           IsStoredMessageOf(method.Parameters[0].Type, payloadType) &&
           method.Parameters[1].Type.ToDisplayString() == "PatternKit.Messaging.MessageContext";

    private static bool IsStoredMessageOf(ITypeSymbol type, INamedTypeSymbol payloadType)
        => type is INamedTypeSymbol named &&
           named.ConstructedFrom.ToDisplayString() == "PatternKit.Messaging.Storage.StoredMessage<TPayload>" &&
           SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], payloadType);

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol payloadType, IMethodSymbol[] handlers, string factoryName, string subscriberName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Consumers.DurableSubscriber<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append("> ").Append(factoryName).Append("(global::PatternKit.Messaging.Storage.MessageStore<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .AppendLine("> store, global::PatternKit.Messaging.Consumers.IDurableSubscriberCheckpointStore checkpoints)");
        sb.Append("        => global::PatternKit.Messaging.Consumers.DurableSubscriber<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(">.Create(").Append(ToLiteral(subscriberName)).AppendLine(")");
        sb.AppendLine("            .From(store)");
        sb.AppendLine("            .TrackWith(checkpoints)");
        foreach (var handler in handlers)
            sb.Append("            .Handle(").Append(ToLiteral(GetHandlerName(handler))).Append(", ").Append(handler.Name).AppendLine(")");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetHandlerName(IMethodSymbol handler)
    {
        var attr = handler.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.DurableSubscriberHandlerAttribute");
        return attr.ConstructorArguments.Length > 0 ? (string?)attr.ConstructorArguments[0].Value ?? handler.Name : handler.Name;
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
