using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class EventDrivenConsumerGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("PKEVT001", "Event-driven consumer type must be partial", "Type '{0}' is marked with [GenerateEventDrivenConsumer] but is not declared as partial", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingHandler = new("PKEVT002", "Event-driven consumer handler is missing", "Type '{0}' must declare at least one [EventDrivenConsumerHandler] method", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidHandler = new("PKEVT003", "Event-driven consumer handler signature is invalid", "Handler '{0}' must be static and return EventDrivenConsumerHandlerResult with Message<TPayload> and MessageContext parameters", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GenerateEventDrivenConsumerAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GenerateEventDrivenConsumerAttribute");
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (payloadType is null)
            return;

        var handlers = type.GetMembers().OfType<IMethodSymbol>().Where(static method =>
            method.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.EventDrivenConsumerHandlerAttribute")).ToArray();
        if (handlers.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingHandler, node.Identifier.GetLocation(), type.Name));
            return;
        }

        foreach (var handler in handlers)
        {
            if (!IsHandler(handler, payloadType))
            {
                context.ReportDiagnostic(Diagnostic.Create(InvalidHandler, handler.Locations.FirstOrDefault(), handler.Name));
                return;
            }
        }

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var consumerName = GetNamedString(attribute, "ConsumerName") ?? "event-driven-consumer";

        context.AddSource($"{type.Name}.EventDrivenConsumer.g.cs", SourceText.From(GenerateSource(type, payloadType, handlers, factoryName, consumerName), Encoding.UTF8));
    }

    private static bool IsHandler(IMethodSymbol method, INamedTypeSymbol payloadType)
        => method.IsStatic &&
           method.ReturnType.ToDisplayString() == "PatternKit.Messaging.Consumers.EventDrivenConsumerHandlerResult" &&
           method.Parameters.Length == 2 &&
           IsMessageOf(method.Parameters[0].Type, payloadType) &&
           method.Parameters[1].Type.ToDisplayString() == "PatternKit.Messaging.MessageContext";

    private static bool IsMessageOf(ITypeSymbol type, INamedTypeSymbol payloadType)
        => type is INamedTypeSymbol named &&
           named.ConstructedFrom.ToDisplayString() == "PatternKit.Messaging.Message<TPayload>" &&
           SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], payloadType);

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol payloadType, IMethodSymbol[] handlers, string factoryName, string consumerName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Consumers.EventDrivenConsumer<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append("> ").Append(factoryName).AppendLine("()");
        sb.Append("        => global::PatternKit.Messaging.Consumers.EventDrivenConsumer<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(">.Create(").Append(ToLiteral(consumerName)).AppendLine(")");
        foreach (var handler in handlers)
        {
            var handlerName = GetHandlerName(handler);
            sb.Append("            .Handle(").Append(ToLiteral(handlerName)).Append(", ").Append(handler.Name).AppendLine(")");
        }

        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetHandlerName(IMethodSymbol handler)
    {
        var attr = handler.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.EventDrivenConsumerHandlerAttribute");
        return attr.ConstructorArguments.Length > 0 ? (string?)attr.ConstructorArguments[0].Value ?? handler.Name : handler.Name;
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
