using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class GuaranteedDeliveryGenerator : IIncrementalGenerator
{
    private const string AttributeName = "PatternKit.Generators.Messaging.GenerateGuaranteedDeliveryAttribute";

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKMGD001",
        "Guaranteed Delivery type must be partial",
        "Type '{0}' is marked with [GenerateGuaranteedDelivery] but is not declared as partial",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidConfiguration = new(
        "PKMGD002",
        "Guaranteed Delivery configuration is invalid",
        "Type '{0}' has invalid Guaranteed Delivery configuration: factory and queue names are required, lease must be positive, and max attempts must be positive",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == AttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length == 1
            ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
            : null;
        if (payloadType is null)
            return;

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var queueName = GetNamedString(attribute, "QueueName") ?? "guaranteed-delivery";
        var leaseMilliseconds = GetNamedInt(attribute, "LeaseMilliseconds") ?? 300000;
        var maxDeliveryAttempts = GetNamedInt(attribute, "MaxDeliveryAttempts") ?? 5;
        if (string.IsNullOrWhiteSpace(factoryName) ||
            string.IsNullOrWhiteSpace(queueName) ||
            leaseMilliseconds <= 0 ||
            maxDeliveryAttempts <= 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidConfiguration, node.Identifier.GetLocation(), type.Name));
            return;
        }

        context.AddSource($"{type.Name}.GuaranteedDelivery.g.cs", SourceText.From(
            GenerateSource(type, payloadType, factoryName, queueName, leaseMilliseconds, maxDeliveryAttempts),
            Encoding.UTF8));
    }

    private static string GenerateSource(
        INamedTypeSymbol type,
        INamedTypeSymbol payloadType,
        string factoryName,
        string queueName,
        int leaseMilliseconds,
        int maxDeliveryAttempts)
    {
        var payloadName = payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Reliability.GuaranteedDeliveryQueue<")
            .Append(payloadName).Append("> ").Append(factoryName).AppendLine("()");
        sb.Append("        => global::PatternKit.Messaging.Reliability.GuaranteedDeliveryQueue<")
            .Append(payloadName).AppendLine(">.Create(");
        sb.Append("            new global::PatternKit.Messaging.Reliability.InMemoryGuaranteedDeliveryStore<")
            .Append(payloadName).AppendLine(">())");
        sb.Append("            .Name(").Append(ToLiteral(queueName)).AppendLine(")");
        sb.Append("            .LeaseDuration(global::System.TimeSpan.FromMilliseconds(").Append(leaseMilliseconds).AppendLine("))");
        sb.Append("            .MaxDeliveryAttempts(").Append(maxDeliveryAttempts).AppendLine(")");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static int? GetNamedInt(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as int?;

    private static string ToLiteral(string value)
        => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
