using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class InvalidMessageChannelGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("PKIMC001", "Invalid message channel type must be partial", "Type '{0}' is marked with [GenerateInvalidMessageChannel] but is not declared as partial", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GenerateInvalidMessageChannelAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GenerateInvalidMessageChannelAttribute");
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (payloadType is null)
            return;

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var channelName = GetNamedString(attribute, "ChannelName") ?? "invalid-message-channel";

        context.AddSource($"{type.Name}.InvalidMessageChannel.g.cs", SourceText.From(GenerateSource(type, payloadType, factoryName, channelName), Encoding.UTF8));
    }

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol payloadType, string factoryName, string channelName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        var payload = payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Channels.InvalidMessageChannel<").Append(payload).Append(">.Builder ").Append(factoryName)
            .Append("(global::PatternKit.Messaging.Channels.MessageChannel<global::PatternKit.Messaging.Channels.InvalidMessage<").Append(payload).AppendLine(">> invalidChannel)");
        sb.Append("        => global::PatternKit.Messaging.Channels.InvalidMessageChannel<").Append(payload).Append(">.Create(").Append(ToLiteral(channelName)).AppendLine(")");
        sb.AppendLine("            .To(invalidChannel);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
