using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class MessagingGatewayGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("PKGWY001", "Messaging gateway type must be partial", "Type '{0}' is marked with [GenerateMessagingGateway] but is not declared as partial", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingHandler = new("PKGWY002", "Messaging gateway handler is missing", "Type '{0}' must declare exactly one [MessagingGatewayHandler] method", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidHandler = new("PKGWY003", "Messaging gateway handler signature is invalid", "Handler '{0}' must be static and return Message<TResponse> with Message<TRequest> and MessageContext parameters", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GenerateMessagingGatewayAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GenerateMessagingGatewayAttribute");
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var requestType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        var responseType = attribute.ConstructorArguments.Length > 1 ? attribute.ConstructorArguments[1].Value as INamedTypeSymbol : null;
        if (requestType is null || responseType is null)
            return;

        var handlers = type.GetMembers().OfType<IMethodSymbol>().Where(static method =>
            method.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.MessagingGatewayHandlerAttribute")).ToArray();
        if (handlers.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingHandler, node.Identifier.GetLocation(), type.Name));
            return;
        }

        if (!IsHandler(handlers[0], requestType, responseType))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidHandler, handlers[0].Locations.FirstOrDefault(), handlers[0].Name));
            return;
        }

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var gatewayName = GetNamedString(attribute, "GatewayName") ?? "messaging-gateway";
        context.AddSource($"{type.Name}.MessagingGateway.g.cs", SourceText.From(GenerateSource(type, requestType, responseType, handlers[0].Name, factoryName, gatewayName), Encoding.UTF8));
    }

    private static bool IsHandler(IMethodSymbol method, INamedTypeSymbol requestType, INamedTypeSymbol responseType)
        => method.IsStatic &&
           IsMessageOf(method.ReturnType, responseType) &&
           method.Parameters.Length == 2 &&
           IsMessageOf(method.Parameters[0].Type, requestType) &&
           method.Parameters[1].Type.ToDisplayString() == "PatternKit.Messaging.MessageContext";

    private static bool IsMessageOf(ITypeSymbol type, INamedTypeSymbol payloadType)
        => type is INamedTypeSymbol named &&
           named.ConstructedFrom.ToDisplayString() == "PatternKit.Messaging.Message<TPayload>" &&
           SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], payloadType);

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol requestType, INamedTypeSymbol responseType, string handler, string factoryName, string gatewayName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Gateways.MessagingGateway<")
            .Append(requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(", ")
            .Append(responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append("> ").Append(factoryName).AppendLine("(");
        sb.Append("        global::PatternKit.Messaging.Channels.MessageChannel<")
            .Append(requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .AppendLine("> requestChannel)");
        sb.Append("        => global::PatternKit.Messaging.Gateways.MessagingGateway<")
            .Append(requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(", ")
            .Append(responseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(">.Create(").Append(ToLiteral(gatewayName)).AppendLine(")");
        sb.AppendLine("            .SendTo(requestChannel)");
        sb.Append("            .Handle(").Append(handler).AppendLine(")");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
