using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class MessageExpirationGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKMEXP001",
        "Message expiration type must be partial",
        "Type '{0}' is marked with [GenerateMessageExpiration] but is not declared as partial",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidConfiguration = new(
        "PKMEXP002",
        "Message expiration configuration is invalid",
        "Type '{0}' has invalid message-expiration configuration: factory, policy, header, and reason values must not be empty",
        "PatternKit.Generators.Messaging",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GenerateMessageExpirationAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GenerateMessageExpirationAttribute");
            if (attr is null)
                return;

            Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(
        SourceProductionContext context,
        INamedTypeSymbol type,
        TypeDeclarationSyntax node,
        AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length >= 1
            ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
            : null;
        if (payloadType is null)
            return;

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var policyName = GetNamedString(attribute, "PolicyName") ?? "message-expiration";
        var headerName = GetNamedString(attribute, "HeaderName") ?? "expires-at";
        var expiredReason = GetNamedString(attribute, "ExpiredReason") ?? "Message expired before processing.";
        if (string.IsNullOrWhiteSpace(factoryName) ||
            string.IsNullOrWhiteSpace(policyName) ||
            string.IsNullOrWhiteSpace(headerName) ||
            string.IsNullOrWhiteSpace(expiredReason))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidConfiguration, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var ttlMilliseconds = GetNamedInt(attribute, "DefaultTtlMilliseconds");
        var preserveExisting = GetNamedBool(attribute, "PreserveExisting", defaultValue: true);

        context.AddSource($"{type.Name}.MessageExpiration.g.cs", SourceText.From(
            GenerateSource(type, payloadType, factoryName, policyName, headerName, ttlMilliseconds, preserveExisting, expiredReason),
            Encoding.UTF8));
    }

    private static string GenerateSource(
        INamedTypeSymbol type,
        INamedTypeSymbol payloadType,
        string factoryName,
        string policyName,
        string headerName,
        int ttlMilliseconds,
        bool preserveExisting,
        string expiredReason)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(GetKind(type)).Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Reliability.MessageExpiration<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append("> ")
            .Append(factoryName)
            .AppendLine("()");
        sb.Append("        => global::PatternKit.Messaging.Reliability.MessageExpiration<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .AppendLine(">.Create()");
        sb.Append("            .Name(").Append(ToLiteral(policyName)).AppendLine(")");
        sb.Append("            .Header(").Append(ToLiteral(headerName)).AppendLine(")");
        if (ttlMilliseconds > 0)
            sb.Append("            .DefaultTtl(global::System.TimeSpan.FromMilliseconds(").Append(ttlMilliseconds).AppendLine("))");
        sb.Append("            .PreserveExisting(").Append(preserveExisting ? "true" : "false").AppendLine(")");
        sb.Append("            .ExpiredReason(").Append(ToLiteral(expiredReason)).AppendLine(")");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetKind(INamedTypeSymbol type)
        => type.TypeKind == TypeKind.Struct ? "struct" : "class";

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static int GetNamedInt(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as int? ?? 0;

    private static bool GetNamedBool(AttributeData attribute, string name, bool defaultValue)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as bool? ?? defaultValue;

    private static string ToLiteral(string value)
        => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
