using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class PollingConsumerGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("PKPOLL001", "Polling consumer type must be partial", "Type '{0}' is marked with [GeneratePollingConsumer] but is not declared as partial", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingSource = new("PKPOLL002", "Polling consumer source is missing", "Type '{0}' must declare exactly one [PollingConsumerSource] method", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidSource = new("PKPOLL003", "Polling consumer source signature is invalid", "Source '{0}' must be static and return Message<TPayload>? with a MessageContext parameter", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GeneratePollingConsumerAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GeneratePollingConsumerAttribute");
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (payloadType is null)
            return;

        var sources = type.GetMembers().OfType<IMethodSymbol>().Where(static method =>
            method.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.PollingConsumerSourceAttribute")).ToArray();
        if (sources.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingSource, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var source = sources[0];
        if (!IsSource(source, payloadType))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidSource, source.Locations.FirstOrDefault(), source.Name));
            return;
        }

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var consumerName = GetNamedString(attribute, "ConsumerName") ?? "polling-consumer";

        context.AddSource($"{type.Name}.PollingConsumer.g.cs", SourceText.From(GenerateSource(type, payloadType, source.Name, factoryName, consumerName), Encoding.UTF8));
    }

    private static bool IsSource(IMethodSymbol method, INamedTypeSymbol payloadType)
        => method.IsStatic &&
           IsMessageOf(method.ReturnType, payloadType) &&
           method.Parameters.Length == 1 &&
           method.Parameters[0].Type.ToDisplayString() == "PatternKit.Messaging.MessageContext";

    private static bool IsMessageOf(ITypeSymbol type, INamedTypeSymbol payloadType)
        => type is INamedTypeSymbol named &&
           named.ConstructedFrom.ToDisplayString() == "PatternKit.Messaging.Message<TPayload>" &&
           SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], payloadType);

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol payloadType, string source, string factoryName, string consumerName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Consumers.PollingConsumer<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append("> ").Append(factoryName).AppendLine("()");
        sb.Append("        => global::PatternKit.Messaging.Consumers.PollingConsumer<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(">.Create(").Append(ToLiteral(consumerName)).AppendLine(")");
        sb.Append("            .From(").Append(source).AppendLine(")");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
