using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.Messaging;

[Generator]
public sealed class ResequencerGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MustBePartial = new("PKRSEQ001", "Resequencer type must be partial", "Type '{0}' is marked with [GenerateResequencer] but is not declared as partial", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingSelector = new("PKRSEQ002", "Resequencer has no sequence selector", "Type '{0}' must declare exactly one [ResequencerSequence] method", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidSelector = new("PKRSEQ003", "Resequencer sequence selector signature is invalid", "Selector '{0}' must be static long Method(Message<TPayload>, MessageContext)", "PatternKit.Generators.Messaging", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Messaging.GenerateResequencerAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.GenerateResequencerAttribute");
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var payloadType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (payloadType is null)
            return;

        var selectors = type.GetMembers().OfType<IMethodSymbol>().Where(static method =>
            method.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Messaging.ResequencerSequenceAttribute")).ToArray();
        if (selectors.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingSelector, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var selector = selectors[0];
        if (!IsSelector(selector, payloadType))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidSelector, selector.Locations.FirstOrDefault(), selector.Name));
            return;
        }

        var factoryName = GetNamedString(attribute, "FactoryName") ?? "Create";
        var name = GetNamedString(attribute, "Name") ?? "resequencer";
        var startsAt = GetNamedLong(attribute, "StartsAt") ?? 1;
        context.AddSource($"{type.Name}.Resequencer.g.cs", SourceText.From(GenerateSource(type, payloadType, selector.Name, factoryName, name, startsAt), Encoding.UTF8));
    }

    private static bool IsSelector(IMethodSymbol method, INamedTypeSymbol payloadType)
        => method.IsStatic &&
           method.ReturnType.SpecialType == SpecialType.System_Int64 &&
           method.Parameters.Length == 2 &&
           method.Parameters[0].Type is INamedTypeSymbol named &&
           named.ConstructedFrom.ToDisplayString() == "PatternKit.Messaging.Message<TPayload>" &&
           SymbolEqualityComparer.Default.Equals(named.TypeArguments[0], payloadType) &&
           method.Parameters[1].Type.ToDisplayString() == "PatternKit.Messaging.MessageContext";

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol payloadType, string selector, string factoryName, string name, long startsAt)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Messaging.Routing.Resequencer<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append("> ").Append(factoryName).AppendLine("()");
        sb.Append("        => global::PatternKit.Messaging.Routing.Resequencer<")
            .Append(payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(">.Create(").Append(ToLiteral(name)).AppendLine(")");
        sb.Append("            .SelectSequence(").Append(selector).AppendLine(")");
        sb.Append("            .StartsAt(").Append(startsAt).AppendLine(")");
        sb.AppendLine("            .Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static long? GetNamedLong(AttributeData attribute, string name)
    {
        var value = attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value;
        return value is long typed ? typed : null;
    }

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
