using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.LazyLoading;

[Generator]
public sealed class LazyLoadGenerator : IIncrementalGenerator
{
    private const string GenerateLazyLoadAttributeName = "PatternKit.Generators.LazyLoading.GenerateLazyLoadAttribute";

    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKLL001",
        "Lazy load host must be partial",
        "Type '{0}' is marked with [GenerateLazyLoad] but is not declared as partial",
        "PatternKit.Generators.LazyLoading",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidConfiguration = new(
        "PKLL002",
        "Lazy load configuration is invalid",
        "Lazy load '{0}' must have TimeToLiveMilliseconds >= 0",
        "PatternKit.Generators.LazyLoading",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidIdentifier = new(
        "PKLL003",
        "Lazy load member name is invalid",
        "Lazy load '{0}' has an invalid member name '{1}'",
        "PatternKit.Generators.LazyLoading",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateLazyLoadAttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static a =>
                a.AttributeClass?.ToDisplayString() == GenerateLazyLoadAttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var valueType = attribute.ConstructorArguments.Length >= 1
            ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
            : null;
        if (valueType is null)
            return;

        var ttl = GetNamedInt(attribute, "TimeToLiveMilliseconds") ?? 0;
        if (ttl < 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidConfiguration, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var factoryMethodName = GetNamedString(attribute, "FactoryMethodName") ?? "Create";
        if (!IsIdentifier(factoryMethodName))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidIdentifier, node.Identifier.GetLocation(), type.Name, factoryMethodName));
            return;
        }

        var loaderMethodName = GetNamedString(attribute, "LoaderMethodName") ?? "LoadAsync";
        if (!IsIdentifier(loaderMethodName))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidIdentifier, node.Identifier.GetLocation(), type.Name, loaderMethodName));
            return;
        }

        var name = GetNamedString(attribute, "LazyLoadName") ?? "lazy-load";
        var cacheEnabled = GetNamedBool(attribute, "CacheEnabled") ?? true;
        context.AddSource($"{type.Name}.LazyLoad.g.cs", SourceText.From(
            GenerateSource(type, valueType, factoryMethodName, loaderMethodName, name, cacheEnabled, ttl),
            Encoding.UTF8));
    }

    private static string GenerateSource(
        INamedTypeSymbol type,
        INamedTypeSymbol valueType,
        string factoryMethodName,
        string loaderMethodName,
        string name,
        bool cacheEnabled,
        int ttl)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var valueTypeName = valueType.ToDisplayString(TypeFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        var containingTypes = GetContainingTypes(type);
        var indentLevel = 0;
        foreach (var containingType in containingTypes)
        {
            AppendTypeDeclaration(sb, containingType, indentLevel);
            sb.AppendLine();
            sb.AppendLine(new string(' ', indentLevel * 4) + "{");
            indentLevel++;
        }

        AppendTypeDeclaration(sb, type, indentLevel);
        sb.AppendLine();
        var indent = new string(' ', indentLevel * 4);
        sb.AppendLine(indent + "{");
        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";
        sb.Append(memberIndent).Append("public static global::PatternKit.Application.LazyLoading.LazyLoad<").Append(valueTypeName).Append("> ").Append(factoryMethodName).AppendLine("()");
        sb.AppendLine(memberIndent + "{");
        sb.Append(bodyIndent).Append("var builder = global::PatternKit.Application.LazyLoading.LazyLoad<").Append(valueTypeName).Append(">.Create(\"").Append(Escape(name)).AppendLine("\")");
        sb.Append(bodyIndent).Append("    .LoadWith(").Append(loaderMethodName).AppendLine(");");
        if (!cacheEnabled)
            sb.AppendLine(bodyIndent + "builder.DisableCache();");
        if (ttl > 0)
            sb.Append(bodyIndent).Append("builder.WithTimeToLive(global::System.TimeSpan.FromMilliseconds(").Append(ttl).AppendLine("));");
        sb.AppendLine(bodyIndent + "return builder.Build();");
        sb.AppendLine(memberIndent + "}");
        sb.AppendLine(indent + "}");
        for (var i = containingTypes.Length - 1; i >= 0; i--)
            sb.AppendLine(new string(' ', i * 4) + "}");

        return sb.ToString();
    }

    private static INamedTypeSymbol[] GetContainingTypes(INamedTypeSymbol type)
    {
        var containingTypes = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
            containingTypes.Push(current);

        return containingTypes.ToArray();
    }

    private static void AppendTypeDeclaration(StringBuilder sb, INamedTypeSymbol type, int indentLevel)
    {
        sb.Append(new string(' ', indentLevel * 4));
        sb.Append(GetAccessibility(type.DeclaredAccessibility)).Append(' ');
        if (type.IsStatic)
            sb.Append("static ");
        else if (type.IsAbstract && type.TypeKind == TypeKind.Class)
            sb.Append("abstract ");
        else if (type.IsSealed && type.TypeKind == TypeKind.Class)
            sb.Append("sealed ");
        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name);
    }

    private static bool IsIdentifier(string value)
        => SyntaxFacts.IsValidIdentifier(value) && SyntaxFacts.GetKeywordKind(value) == SyntaxKind.None;

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static int? GetNamedInt(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as int?;

    private static bool? GetNamedBool(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as bool?;
}
