name: Bug Report
description: File a bug report to help us improve PatternKit
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - jerrettdavis

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a pattern with '...'
        2. Call method '....'
        3. Pass parameters '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core Library
        - Generators
        - Source Generation
        - Behavioral Patterns
        - Creational Patterns
        - Structural Patterns
        - Documentation
        - Examples
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of PatternKit are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What version of .NET are you using?
      options:
        - ".NET 10.0"
        - ".NET 9.0"
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Windows 11, Ubuntu 22.04, macOS 14"
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue.
      render: csharp
      placeholder: |
        var strategy = Strategy<int, string>.Create()
            .When(i => i > 0).Then(i => "positive")
            .Build();

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Please copy and paste any relevant log output or stack traces.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
