using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.ValueObjects;

[Generator]
public sealed class ValueObjectGenerator : IIncrementalGenerator
{
    private const string GenerateValueObjectAttributeName = "PatternKit.Generators.ValueObjects.GenerateValueObjectAttribute";
    private const string ValueObjectComponentAttributeName = "PatternKit.Generators.ValueObjects.ValueObjectComponentAttribute";

    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKVO001",
        "Value object must be partial",
        "Type '{0}' is marked with [GenerateValueObject] but is not declared as partial",
        "PatternKit.Generators.ValueObjects",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor MustBeClass = new(
        "PKVO002",
        "Value object generator supports classes",
        "Type '{0}' is marked with [GenerateValueObject] but is not a class",
        "PatternKit.Generators.ValueObjects",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor MissingComponents = new(
        "PKVO003",
        "Value object has no components",
        "Type '{0}' is marked with [GenerateValueObject] but does not declare any [ValueObjectComponent] properties",
        "PatternKit.Generators.ValueObjects",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateValueObjectAttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static a =>
                a.AttributeClass?.ToDisplayString() == GenerateValueObjectAttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (type.TypeKind != TypeKind.Class)
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBeClass, node.Identifier.GetLocation(), type.Name));
            return;
        }

        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var components = GetComponents(type);
        if (components.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingComponents, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var factoryMethodName = GetNamedString(attribute, "FactoryMethodName") ?? "Create";
        context.AddSource($"{type.Name}.ValueObject.g.cs", SourceText.From(
            GenerateSource(type, components, factoryMethodName),
            Encoding.UTF8));
    }

    private static ImmutableArray<IPropertySymbol> GetComponents(INamedTypeSymbol type)
        => type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property => property.GetAttributes().Any(static attr =>
                attr.AttributeClass?.ToDisplayString() == ValueObjectComponentAttributeName))
            .OrderBy(static property => property.Locations.FirstOrDefault()?.SourceSpan.Start ?? 0)
            .ToImmutableArray();

    private static string GenerateSource(INamedTypeSymbol type, IReadOnlyList<IPropertySymbol> components, string factoryMethodName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        var typeName = type.Name;
        sb.Append("partial class ").Append(typeName)
            .Append(" : global::System.IEquatable<").Append(typeName).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    public static ").Append(typeName).Append(' ').Append(factoryMethodName).Append('(')
            .Append(string.Join(", ", components.Select(static c => $"{c.Type.ToDisplayString(TypeFormat)} {ToParameterName(c.Name)}")))
            .AppendLine(")");
        sb.Append("        => new(").Append(string.Join(", ", components.Select(static c => ToParameterName(c.Name)))).AppendLine(");");
        sb.AppendLine();
        sb.Append("    public bool Equals(").Append(typeName).AppendLine("? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (global::System.Object.ReferenceEquals(null, other))");
        sb.AppendLine("            return false;");
        sb.AppendLine("        if (global::System.Object.ReferenceEquals(this, other))");
        sb.AppendLine("            return true;");
        sb.Append("        return ");
        sb.Append(string.Join(" && ", components.Select(static c => $"global::System.Collections.Generic.EqualityComparer<{c.Type.ToDisplayString(TypeFormat)}>.Default.Equals({c.Name}, other.{c.Name})")));
        sb.AppendLine(";");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override bool Equals(object? obj)");
        sb.Append("        => obj is ").Append(typeName).AppendLine(" other && Equals(other);");
        sb.AppendLine();
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        var hash = new global::System.HashCode();");
        foreach (var component in components)
            sb.Append("        hash.Add(").Append(component.Name).AppendLine(");");
        sb.AppendLine("        return hash.ToHashCode();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    public static bool operator ==(").Append(typeName).Append("? left, ").Append(typeName).AppendLine("? right)");
        sb.AppendLine("        => left?.Equals(right) ?? right is null;");
        sb.AppendLine();
        sb.Append("    public static bool operator !=(").Append(typeName).Append("? left, ").Append(typeName).AppendLine("? right)");
        sb.AppendLine("        => !(left == right);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToParameterName(string propertyName)
        => string.IsNullOrEmpty(propertyName)
            ? propertyName
            : char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;
}
