using Microsoft.Extensions.DependencyInjection;

namespace PatternKit.Examples.ProductionReadiness;

/// <summary>
/// Pattern family used by the PatternKit pattern coverage catalog.
/// </summary>
public enum PatternFamily
{
    Creational,
    Structural,
    Behavioral,
    EnterpriseIntegration,
    MessagingReliability,
    CloudArchitecture,
    ApplicationArchitecture
}

/// <summary>
/// Describes a PatternKit implementation path for a design pattern.
/// </summary>
public sealed record PatternImplementationPath(
    string Name,
    string FluentDocumentationPath,
    string FluentSourcePath,
    string FluentTestPath,
    string? GeneratorDocumentationPath,
    string? GeneratorSourcePath,
    string? GeneratorTestPath,
    string? TrackingIssueUrl,
    string ExampleDocumentationPath,
    string ExampleSourcePath,
    string ExampleTestPath)
{
    public bool HasSourceGeneratedPath =>
        !string.IsNullOrWhiteSpace(GeneratorDocumentationPath)
        && !string.IsNullOrWhiteSpace(GeneratorSourcePath)
        && !string.IsNullOrWhiteSpace(GeneratorTestPath);

    public bool HasTrackedGeneratorGap => !string.IsNullOrWhiteSpace(TrackingIssueUrl);
}

/// <summary>
/// Describes one design, integration, or architecture pattern and the PatternKit surfaces that support it.
/// </summary>
public sealed record PatternCoverageDescriptor(
    string Name,
    PatternFamily Family,
    PatternImplementationPath Implementation,
    IReadOnlyList<string> IntegrationNotes);

/// <summary>
/// Read-only catalog of PatternKit's supported and tracked design, integration, and architecture patterns.
/// </summary>
public interface IPatternKitPatternCatalog
{
    IReadOnlyList<PatternCoverageDescriptor> Patterns { get; }
}

/// <summary>
/// Pattern coverage manifest used by docs, tests, and production-readiness audits.
/// </summary>
public sealed class PatternKitPatternCatalog : IPatternKitPatternCatalog
{
    private static readonly IReadOnlyList<PatternCoverageDescriptor> Items =
    [
        Pattern("Abstract Factory", PatternFamily.Creational,
            "docs/patterns/creational/abstract-factory/index.md",
            "src/PatternKit.Core/Creational/AbstractFactory/AbstractFactory.cs",
            "test/PatternKit.Tests/Creational/AbstractFactoryTests.cs",
            "docs/generators/abstract-factory.md",
            "src/PatternKit.Generators/Factories/AbstractFactoryGenerator.cs",
            "test/PatternKit.Generators.Tests/AbstractFactoryGeneratorTests.cs",
            null,
            "docs/examples/abstract-factory-widget-families.md",
            "src/PatternKit.Examples/AbstractFactoryDemo/AbstractFactoryDemo.cs",
            "test/PatternKit.Examples.Tests/AbstractFactoryDemo/AbstractFactoryDemoTests.cs",
            ["fluent family factory", "generated family factory", "example importable through AddPatternKitExamples"]),

        Pattern("Builder", PatternFamily.Creational,
            "docs/patterns/creational/builder/index.md",
            "src/PatternKit.Core/Creational/Builder/MutableBuilder.cs",
            "test/PatternKit.Tests/Creational/Builder/MutableBuilderTests.cs",
            "docs/generators/builder.md",
            "src/PatternKit.Generators/Builders/BuilderGenerator.cs",
            "test/PatternKit.Generators.Tests/BuilderGeneratorTests.cs",
            null,
            "docs/examples/source-generator-application-suite.md",
            "src/PatternKit.Examples/Generators/Builders/CorporateApplicationBuilderDemo/CorporateApplication.cs",
            "test/PatternKit.Examples.Tests/Generators/CorporateApplicationBuilderDemoTests.cs",
            ["fluent builders", "generated builder", "Generic Host module example"]),

        Pattern("Factory Method", PatternFamily.Creational,
            "docs/patterns/creational/factory/index.md",
            "src/PatternKit.Core/Creational/Factory/Factory.cs",
            "test/PatternKit.Tests/Creational/Factory/FactoryTests.cs",
            "docs/generators/factory-method.md",
            "src/PatternKit.Generators/Factories/FactoriesGenerator.cs",
            "test/PatternKit.Generators.Tests/FactoriesGeneratorTests.cs",
            null,
            "docs/examples/source-generator-application-suite.md",
            "src/PatternKit.Examples/Generators/Factories/FactoryGeneratorExamples.cs",
            "test/PatternKit.Examples.Tests/Generators/FactoryGeneratorExamplesTests.cs",
            ["fluent keyed factory", "generated factory method", "startup module creation"]),

        Pattern("Prototype", PatternFamily.Creational,
            "docs/patterns/creational/prototype/index.md",
            "src/PatternKit.Core/Creational/Prototype/Prototype.cs",
            "test/PatternKit.Tests/Creational/Prototype/PrototypeTests.cs",
            "docs/generators/prototype.md",
            "src/PatternKit.Generators/PrototypeGenerator.cs",
            "test/PatternKit.Generators.Tests/PrototypeGeneratorTests.cs",
            null,
            "docs/examples/prototype-demo.md",
            "src/PatternKit.Examples/PrototypeDemo/PrototypeDemo.cs",
            "test/PatternKit.Examples.Tests/PrototypeDemo/PrototypeDemoTests.cs",
            ["fluent clone registry", "generated clone surface", "game character example"]),

        Pattern("Singleton", PatternFamily.Creational,
            "docs/patterns/creational/singleton/index.md",
            "src/PatternKit.Core/Creational/Singleton/Singleton.cs",
            "test/PatternKit.Tests/Creational/Singleton/SingletonTests.cs",
            "docs/generators/singleton.md",
            "src/PatternKit.Generators/Singleton/SingletonGenerator.cs",
            "test/PatternKit.Generators.Tests/SingletonGeneratorTests.cs",
            null,
            "docs/examples/pos-app-state-singleton.md",
            "src/PatternKit.Examples/Singleton/PosAppStateDemo.cs",
            "test/PatternKit.Examples.Tests/Singleton/PosAppStateDemoTests.cs",
            ["fluent singleton", "generated singleton", "DI-safe POS example"]),

        Pattern("Adapter", PatternFamily.Structural,
            "docs/patterns/structural/adapter/index.md",
            "src/PatternKit.Core/Structural/Adapter/Adapter.cs",
            "test/PatternKit.Tests/Structural/Adapters/AdapterTests.cs",
            "docs/generators/adapter.md",
            "src/PatternKit.Generators/Adapter/AdapterGenerator.cs",
            "test/PatternKit.Generators.Tests/AdapterGeneratorTests.cs",
            null,
            "docs/examples/source-generator-application-suite.md",
            "src/PatternKit.Examples/AdapterGeneratorDemo/PaymentAdapter.cs",
            "test/PatternKit.Examples.Tests/AdapterGeneratorDemo/AdapterGeneratorDemoTests.cs",
            ["fluent DTO mapping", "generated adapter", "payment adapter example"]),

        Pattern("Bridge", PatternFamily.Structural,
            "docs/patterns/structural/bridge/index.md",
            "src/PatternKit.Core/Structural/Bridge/Bridge.cs",
            "test/PatternKit.Tests/Structural/Bridge/BridgeTests.cs",
            "docs/generators/bridge.md",
            "src/PatternKit.Generators/Bridge/BridgeGenerator.cs",
            "test/PatternKit.Generators.Tests/BridgeGeneratorTests.cs",
            null,
            "docs/patterns/structural/bridge/real-world-examples.md",
            "src/PatternKit.Examples/BridgeDemo/BridgeDemo.cs",
            "test/PatternKit.Examples.Tests/BridgeDemo/BridgeDemoTests.cs",
            ["fluent abstraction implementation split", "generated bridge", "notification bridge example"]),

        Pattern("Composite", PatternFamily.Structural,
            "docs/patterns/structural/composite/index.md",
            "src/PatternKit.Core/Structural/Composite/Composite.cs",
            "test/PatternKit.Tests/Structural/Composite/CompositeTests.cs",
            "docs/generators/composite.md",
            "src/PatternKit.Generators/Composite/CompositeGenerator.cs",
            "test/PatternKit.Generators.Tests/CompositeGeneratorTests.cs",
            null,
            "docs/patterns/structural/composite/real-world-examples.md",
            "src/PatternKit.Examples/CompositeDemo/CompositeDemo.cs",
            "test/PatternKit.Examples.Tests/CompositeDemo/CompositeDemoTests.cs",
            ["fluent folding", "generated composite", "file system style example"]),

        Pattern("Decorator", PatternFamily.Structural,
            "docs/patterns/structural/decorator/index.md",
            "src/PatternKit.Core/Structural/Decorator/Decorator.cs",
            "test/PatternKit.Tests/Structural/Decorator/DecoratorTests.cs",
            "docs/generators/decorator.md",
            "src/PatternKit.Generators/DecoratorGenerator.cs",
            "test/PatternKit.Generators.Tests/DecoratorGeneratorTests.cs",
            null,
            "docs/examples/payment-processor-decorator.md",
            "src/PatternKit.Examples/PointOfSale/PaymentProcessorDemo.cs",
            "test/PatternKit.Examples.Tests/PointOfSale/PaymentProcessorTests.cs",
            ["fluent wrapping", "generated decorator", "payment processor example"]),

        Pattern("Facade", PatternFamily.Structural,
            "docs/patterns/structural/facade/index.md",
            "src/PatternKit.Core/Structural/Facade/Facade.cs",
            "test/PatternKit.Tests/Structural/Facade/FacadeTests.cs",
            "docs/generators/facade.md",
            "src/PatternKit.Generators/FacadeGenerator.cs",
            "test/PatternKit.Generators.Tests/FacadeGeneratorTests.cs",
            null,
            "docs/examples/messaging-backplane-facade.md",
            "src/PatternKit.Examples/Messaging/BackplaneFacadeDemo.cs",
            "test/PatternKit.Examples.Tests/Messaging/BackplaneFacadeDemoTests.cs",
            ["fluent facade", "generated facade", "messaging backplane example"]),

        Pattern("Flyweight", PatternFamily.Structural,
            "docs/patterns/structural/flyweight/index.md",
            "src/PatternKit.Core/Structural/Flyweight/Flyweight.cs",
            "test/PatternKit.Tests/Structural/Flyweight/FlyweightTests.cs",
            "docs/generators/flyweight.md",
            "src/PatternKit.Generators/Flyweight/FlyweightGenerator.cs",
            "test/PatternKit.Generators.Tests/FlyweightGeneratorTests.cs",
            null,
            "docs/examples/flyweight-glyph-cache.md",
            "src/PatternKit.Examples/FlyweightDemo/FlyweightDemo.cs",
            "test/PatternKit.Examples.Tests/FlyweightDemos/FlyweightDemoTests.cs",
            ["fluent cache", "generated cache", "glyph cache example"]),

        Pattern("Proxy", PatternFamily.Structural,
            "docs/patterns/structural/proxy/index.md",
            "src/PatternKit.Core/Structural/Proxy/Proxy.cs",
            "test/PatternKit.Tests/Structural/Proxy/ProxyTests.cs",
            "docs/generators/proxy.md",
            "src/PatternKit.Generators/ProxyGenerator.cs",
            "test/PatternKit.Generators.Tests/ProxyGeneratorTests.cs",
            null,
            "docs/examples/proxy-demo.md",
            "src/PatternKit.Examples/ProxyDemo/ProxyDemo.cs",
            "test/PatternKit.Examples.Tests/ProxyDemo/ProxyDemoTests.cs",
            ["fluent proxy", "generated proxy", "virtual and protection examples"]),

        Pattern("Chain of Responsibility", PatternFamily.Behavioral,
            "docs/patterns/behavioral/chain/index.md",
            "src/PatternKit.Core/Behavioral/Chain/ActionChain.cs",
            "test/PatternKit.Tests/Behavioral/Chain/ActionChainTests.cs",
            "docs/generators/chain.md",
            "src/PatternKit.Generators/Chain/ChainGenerator.cs",
            "test/PatternKit.Generators.Tests/ChainGeneratorTests.cs",
            null,
            "docs/examples/auth-logging-chain.md",
            "src/PatternKit.Examples/Chain/AuthLoggingDemo.cs",
            "test/PatternKit.Examples.Tests/Chain/AuthLoggingDemoTests.cs",
            ["fluent chain", "generated chain", "request pipeline example"]),

        Pattern("Command", PatternFamily.Behavioral,
            "docs/patterns/behavioral/command/index.md",
            "src/PatternKit.Core/Behavioral/Command/Command.cs",
            "test/PatternKit.Tests/Behavioral/Command/CommandTests.cs",
            "docs/generators/command.md",
            "src/PatternKit.Generators/Command/CommandGenerator.cs",
            "test/PatternKit.Generators.Tests/CommandGeneratorTests.cs",
            null,
            "docs/examples/resilient-checkout-and-mailboxes.md",
            "src/PatternKit.Examples/Messaging/ResilientCheckoutDemo.cs",
            "test/PatternKit.Examples.Tests/Messaging/ResilientCheckoutDemoTests.cs",
            ["fluent command", "generated command", "checkout command example"]),

        Pattern("Interpreter", PatternFamily.Behavioral,
            "docs/patterns/behavioral/interpreter/index.md",
            "src/PatternKit.Core/Behavioral/Interpreter/Interpreter.cs",
            "test/PatternKit.Tests/Behavioral/InterpreterTests.cs",
            "docs/generators/interpreter.md",
            "src/PatternKit.Generators/Interpreter/InterpreterGenerator.cs",
            "test/PatternKit.Generators.Tests/InterpreterGeneratorTests.cs",
            null,
            "docs/patterns/behavioral/interpreter/real-world-examples.md",
            "src/PatternKit.Examples/InterpreterDemo/InterpreterDemo.cs",
            "test/PatternKit.Examples.Tests/InterpreterDemo/InterpreterDemoTests.cs",
            ["fluent interpreter", "generated interpreter", "rules engine example importable through AddPatternKitExamples"]),

        Pattern("Iterator", PatternFamily.Behavioral,
            "docs/patterns/behavioral/iterator/index.md",
            "src/PatternKit.Core/Behavioral/Iterator/Flow.cs",
            "test/PatternKit.Tests/Behavioral/Iterator/FlowTests.cs",
            "docs/generators/iterator.md",
            "src/PatternKit.Generators/Iterator/IteratorGenerator.cs",
            "test/PatternKit.Generators.Tests/IteratorGeneratorTests.cs",
            null,
            "docs/examples/source-generator-application-suite.md",
            "src/PatternKit.Examples/IteratorDemo/IteratorDemo.cs",
            "test/PatternKit.Examples.Tests/IteratorDemo/IteratorDemoTests.cs",
            ["fluent flow", "generated iterator", "paged stream example"]),

        Pattern("Mediator", PatternFamily.Behavioral,
            "docs/patterns/behavioral/mediator/index.md",
            "src/PatternKit.Core/Behavioral/Mediator/Mediator.cs",
            "test/PatternKit.Tests/Behavioral/Mediator/MediatorTests.cs",
            "docs/generators/dispatcher.md",
            "src/PatternKit.Generators/Messaging/DispatcherGenerator.cs",
            "test/PatternKit.Generators.Tests/DispatcherGeneratorTests.cs",
            null,
            "docs/examples/mediator-demo.md",
            "src/PatternKit.Examples/MediatorDemo/Demo.cs",
            "test/PatternKit.Examples.Tests/MediatorDemo/MediatorDemoTests.cs",
            ["fluent mediator", "generated dispatcher mediator", "service collaboration example"]),

        Pattern("Memento", PatternFamily.Behavioral,
            "docs/patterns/behavioral/memento/index.md",
            "src/PatternKit.Core/Behavioral/Memento/Memento.cs",
            "test/PatternKit.Tests/Behavioral/Memento/MementoTests.cs",
            "docs/generators/memento.md",
            "src/PatternKit.Generators/MementoGenerator.cs",
            "test/PatternKit.Generators.Tests/MementoGeneratorTests.cs",
            null,
            "docs/examples/text-editor-memento.md",
            "src/PatternKit.Examples/MementoDemo/MementoDemo.cs",
            "test/PatternKit.Examples.Tests/MementoDemo/MementoDemoTests.cs",
            ["fluent memento", "generated snapshots", "text editor history example"]),

        Pattern("Observer", PatternFamily.Behavioral,
            "docs/patterns/behavioral/observer/index.md",
            "src/PatternKit.Core/Behavioral/Observer/Observer.cs",
            "test/PatternKit.Tests/Behavioral/Observer/ObserverTests.cs",
            "docs/generators/observer.md",
            "src/PatternKit.Generators/Observer/ObserverGenerator.cs",
            "test/PatternKit.Generators.Tests/ObserverGeneratorTests.cs",
            null,
            "docs/examples/observer-demo.md",
            "src/PatternKit.Examples/ObserverDemo/SimpleEventHub.cs",
            "test/PatternKit.Examples.Tests/ObserverDemo/EventHubTests.cs",
            ["fluent observer", "generated observer hub", "event hub example"]),

        Pattern("State", PatternFamily.Behavioral,
            "docs/patterns/behavioral/state/index.md",
            "src/PatternKit.Core/Behavioral/State/StateMachine.cs",
            "test/PatternKit.Tests/Behavioral/State/StateMachineTests.cs",
            "docs/generators/state-machine.md",
            "src/PatternKit.Generators/StateMachineGenerator.cs",
            "test/PatternKit.Generators.Tests/StateMachineGeneratorTests.cs",
            null,
            "docs/examples/state-machine.md",
            "src/PatternKit.Examples/StateDemo/StateDemo.cs",
            "test/PatternKit.Examples.Tests/StateDemo/StateDemoTests.cs",
            ["fluent state machine", "generated state machine", "order lifecycle example"]),

        Pattern("Strategy", PatternFamily.Behavioral,
            "docs/patterns/behavioral/strategy/index.md",
            "src/PatternKit.Core/Behavioral/Strategy/Strategy.cs",
            "test/PatternKit.Tests/Behavioral/Strategy/StrategyTests.cs",
            "docs/generators/strategy.md",
            "src/PatternKit.Generators/StrategyGenerator.cs",
            "test/PatternKit.Generators.Tests/StrategyGeneratorTests.cs",
            null,
            "docs/examples/composed-notification-strategy.md",
            "src/PatternKit.Examples/Strategies/Composed/ComposedStrategies.cs",
            "test/PatternKit.Examples.Tests/Strategies/Composed/ComposedStrategiesTests.cs",
            ["fluent strategy", "generated strategy", "notification channel example"]),

        Pattern("Template Method", PatternFamily.Behavioral,
            "docs/patterns/behavioral/template/index.md",
            "src/PatternKit.Core/Behavioral/Template/TemplateMethod.cs",
            "test/PatternKit.Tests/Behavioral/TemplateMethodTests.cs",
            "docs/generators/template-method-generator.md",
            "src/PatternKit.Generators/TemplateGenerator.cs",
            "test/PatternKit.Generators.Tests/TemplateGeneratorTests.cs",
            null,
            "docs/examples/template-method-demo.md",
            "src/PatternKit.Examples/TemplateDemo/TemplateDemo.cs",
            "test/PatternKit.Examples.Tests/TemplateDemo/TemplateDemoTests.cs",
            ["fluent and base template", "generated template", "import workflow example"]),

        Pattern("Visitor", PatternFamily.Behavioral,
            "docs/patterns/behavioral/visitor/index.md",
            "src/PatternKit.Core/Behavioral/Visitor/Visitor.cs",
            "test/PatternKit.Tests/Behavioral/VisitorTests.cs",
            "docs/generators/visitor-generator.md",
            "src/PatternKit.Generators/VisitorGenerator.cs",
            "test/PatternKit.Generators.Tests/VisitorGeneratorTests.cs",
            null,
            "docs/examples/document-processing-visitor.md",
            "src/PatternKit.Examples/Generators/Visitors/DocumentProcessingDemo.cs",
            "test/PatternKit.Examples.Tests/Generators/VisitorGeneratorExamplesTests.cs",
            ["fluent visitor", "generated visitor", "document processing example"]),

        Pattern("Message Channel", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-channel.md",
            "src/PatternKit.Core/Messaging/Channels/MessageChannel.cs",
            "test/PatternKit.Tests/Messaging/Channels/MessageChannelTests.cs",
            "docs/generators/message-channel.md",
            "src/PatternKit.Generators/Messaging/MessageChannelGenerator.cs",
            "test/PatternKit.Generators.Tests/MessageChannelGeneratorTests.cs",
            null,
            "docs/examples/inventory-message-channel.md",
            "src/PatternKit.Examples/Messaging/InventoryMessageChannelExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/InventoryMessageChannelExampleTests.cs",
            ["fluent typed message queue", "generated channel factory", "DI-importable inventory example"]),

        Pattern("Polling Consumer", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/polling-consumer.md",
            "src/PatternKit.Core/Messaging/Consumers/PollingConsumer.cs",
            "test/PatternKit.Tests/Messaging/Consumers/PollingConsumerTests.cs",
            "docs/generators/polling-consumer.md",
            "src/PatternKit.Generators/Messaging/PollingConsumerGenerator.cs",
            "test/PatternKit.Generators.Tests/PollingConsumerGeneratorTests.cs",
            null,
            "docs/examples/warehouse-polling-consumer.md",
            "src/PatternKit.Examples/Messaging/WarehousePollingConsumerExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/WarehousePollingConsumerExampleTests.cs",
            ["fluent pull consumer", "generated polling source factory", "DI-importable warehouse replenishment example"]),

        Pattern("Event-Driven Consumer", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/event-driven-consumer.md",
            "src/PatternKit.Core/Messaging/Consumers/EventDrivenConsumer.cs",
            "test/PatternKit.Tests/Messaging/Consumers/EventDrivenConsumerTests.cs",
            "docs/generators/event-driven-consumer.md",
            "src/PatternKit.Generators/Messaging/EventDrivenConsumerGenerator.cs",
            "test/PatternKit.Generators.Tests/EventDrivenConsumerGeneratorTests.cs",
            null,
            "docs/examples/order-event-driven-consumer.md",
            "src/PatternKit.Examples/Messaging/OrderEventDrivenConsumerExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/OrderEventDrivenConsumerExampleTests.cs",
            ["fluent push consumer", "generated event handler factory", "DI-importable order event example"]),

        Pattern("Message Envelope", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-envelope.md",
            "src/PatternKit.Core/Messaging/Message.cs",
            "test/PatternKit.Tests/Messaging/MessageTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/MessageEnvelopeGenerator.cs",
            "test/PatternKit.Generators.Tests/MessageEnvelopeGeneratorTests.cs",
            null,
            "docs/examples/generated-message-envelope.md",
            "src/PatternKit.Examples/Messaging/MessageEnvelopeExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/MessageEnvelopeExampleTests.cs",
            ["runtime envelope and headers", "generated required-header contract", "DI-importable envelope example"]),

        Pattern("Message Translator", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-translator.md",
            "src/PatternKit.Core/Messaging/Transformation/MessageTranslator.cs",
            "test/PatternKit.Tests/Messaging/Transformation/MessageTranslatorTests.cs",
            "docs/generators/message-translator.md",
            "src/PatternKit.Generators/Messaging/MessageTranslatorGenerator.cs",
            "test/PatternKit.Generators.Tests/MessageTranslatorGeneratorTests.cs",
            null,
            "docs/examples/generated-message-translator.md",
            "src/PatternKit.Examples/Messaging/PartnerEventTranslatorExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/PartnerEventTranslatorExampleTests.cs",
            ["fluent payload translator", "generated translator factory", "DI-importable partner event normalization example"]),

        Pattern("Claim Check", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/claim-check.md",
            "src/PatternKit.Core/Messaging/Transformation/ClaimCheck.cs",
            "test/PatternKit.Tests/Messaging/Transformation/ClaimCheckTests.cs",
            "docs/generators/claim-check.md",
            "src/PatternKit.Generators/Messaging/ClaimCheckGenerator.cs",
            "test/PatternKit.Generators.Tests/ClaimCheckGeneratorTests.cs",
            null,
            "docs/examples/generated-claim-check.md",
            "src/PatternKit.Examples/Messaging/LargeDocumentClaimCheckExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/LargeDocumentClaimCheckExampleTests.cs",
            ["fluent payload check-in/restore", "generated claim check factory", "DI-importable large document workflow example"]),

        Pattern("Dead Letter Channel", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/dead-letter-channel.md",
            "src/PatternKit.Core/Messaging/Reliability/DeadLetterChannel.cs",
            "test/PatternKit.Tests/Messaging/Reliability/DeadLetterChannelTests.cs",
            "docs/generators/dead-letter-channel.md",
            "src/PatternKit.Generators/Messaging/DeadLetterChannelGenerator.cs",
            "test/PatternKit.Generators.Tests/DeadLetterChannelGeneratorTests.cs",
            null,
            "docs/examples/generated-dead-letter-channel.md",
            "src/PatternKit.Examples/Messaging/FulfillmentDeadLetterChannelExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/FulfillmentDeadLetterChannelExampleTests.cs",
            ["fluent failure channel", "generated dead-letter channel factory", "DI-importable fulfillment failure workflow example"]),

        Pattern("Content-Based Router", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-routing.md",
            "src/PatternKit.Core/Messaging/Routing/ContentRouter.cs",
            "test/PatternKit.Tests/Messaging/Routing/ContentRouterTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/ContentRouterGenerator.cs",
            "test/PatternKit.Generators.Tests/ContentRouterGeneratorTests.cs",
            null,
            "docs/examples/enterprise-messaging-workflows.md",
            "src/PatternKit.Examples/Messaging/ContentRouterGeneratorExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/ContentRouterGeneratorExampleTests.cs",
            ["fluent content router", "generated content router", "message routing example"]),

        Pattern("Message Filter", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-filter.md",
            "src/PatternKit.Core/Messaging/Routing/MessageFilter.cs",
            "test/PatternKit.Tests/Messaging/Routing/MessageFilterTests.cs",
            "docs/generators/message-filter.md",
            "src/PatternKit.Generators/Messaging/MessageFilterGenerator.cs",
            "test/PatternKit.Generators.Tests/MessageFilterGeneratorTests.cs",
            null,
            "docs/examples/order-message-filter.md",
            "src/PatternKit.Examples/Messaging/OrderMessageFilterExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/OrderMessageFilterExampleTests.cs",
            ["fluent message filter", "generated allow-rule filter", "DI-importable order fraud-screening example"]),

        Pattern("Message Store", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-store.md",
            "src/PatternKit.Core/Messaging/Storage/MessageStore.cs",
            "test/PatternKit.Tests/Messaging/Storage/MessageStoreTests.cs",
            "docs/generators/message-store.md",
            "src/PatternKit.Generators/Messaging/MessageStoreGenerator.cs",
            "test/PatternKit.Generators.Tests/MessageStoreGeneratorTests.cs",
            null,
            "docs/examples/order-message-store.md",
            "src/PatternKit.Examples/Messaging/OrderMessageStoreExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/OrderMessageStoreExampleTests.cs",
            ["fluent message store", "generated identity and retention hooks", "DI-importable order audit/replay example"]),

        Pattern("Wire Tap", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/wire-tap.md",
            "src/PatternKit.Core/Messaging/Routing/WireTap.cs",
            "test/PatternKit.Tests/Messaging/Routing/WireTapTests.cs",
            "docs/generators/wire-tap.md",
            "src/PatternKit.Generators/Messaging/WireTapGenerator.cs",
            "test/PatternKit.Generators.Tests/WireTapGeneratorTests.cs",
            null,
            "docs/examples/order-wire-tap.md",
            "src/PatternKit.Examples/Messaging/OrderWireTapExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/OrderWireTapExampleTests.cs",
            ["fluent wire tap", "generated tap handler factory", "DI-importable order observability example"]),

        Pattern("Control Bus", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/control-bus.md",
            "src/PatternKit.Core/Messaging/ControlBus/ControlBus.cs",
            "test/PatternKit.Tests/Messaging/ControlBus/ControlBusTests.cs",
            "docs/generators/control-bus.md",
            "src/PatternKit.Generators/Messaging/ControlBusGenerator.cs",
            "test/PatternKit.Generators.Tests/ControlBusGeneratorTests.cs",
            null,
            "docs/examples/fulfillment-control-bus.md",
            "src/PatternKit.Examples/Messaging/FulfillmentControlBusExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/FulfillmentControlBusExampleTests.cs",
            ["fluent control bus", "generated operational command bus", "DI-importable fulfillment control example"]),

        Pattern("Scatter-Gather", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/scatter-gather.md",
            "src/PatternKit.Core/Messaging/Routing/ScatterGather.cs",
            "test/PatternKit.Tests/Messaging/Routing/ScatterGatherTests.cs",
            "docs/generators/scatter-gather.md",
            "src/PatternKit.Generators/Messaging/ScatterGatherGenerator.cs",
            "test/PatternKit.Generators.Tests/ScatterGatherGeneratorTests.cs",
            null,
            "docs/examples/supplier-quote-scatter-gather.md",
            "src/PatternKit.Examples/Messaging/SupplierQuoteScatterGatherExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/SupplierQuoteScatterGatherExampleTests.cs",
            ["fluent scatter-gather", "generated quote fan-out", "DI-importable supplier quote example"]),

        Pattern("Resequencer", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/resequencer.md",
            "src/PatternKit.Core/Messaging/Routing/Resequencer.cs",
            "test/PatternKit.Tests/Messaging/Routing/ResequencerTests.cs",
            "docs/generators/resequencer.md",
            "src/PatternKit.Generators/Messaging/ResequencerGenerator.cs",
            "test/PatternKit.Generators.Tests/ResequencerGeneratorTests.cs",
            null,
            "docs/examples/shipment-resequencer.md",
            "src/PatternKit.Examples/Messaging/ShipmentResequencerExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/ShipmentResequencerExampleTests.cs",
            ["fluent resequencer", "generated sequence selector factory", "DI-importable shipment sequencing example"]),

        Pattern("Recipient List", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-routing.md",
            "src/PatternKit.Core/Messaging/Routing/RecipientList.cs",
            "test/PatternKit.Tests/Messaging/Routing/RecipientListTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/RecipientListGenerator.cs",
            "test/PatternKit.Generators.Tests/RecipientListGeneratorTests.cs",
            null,
            "docs/examples/generated-recipient-list.md",
            "src/PatternKit.Examples/Messaging/RecipientListGeneratorExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/RecipientListGeneratorExampleTests.cs",
            ["fluent recipient list", "generated recipient list", "DI-importable fan-out example"]),

        Pattern("Competing Consumers", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/competing-consumers.md",
            "src/PatternKit.Core/Messaging/CompetingConsumers/CompetingConsumerGroup.cs",
            "test/PatternKit.Tests/Messaging/CompetingConsumers/CompetingConsumerGroupTests.cs",
            "docs/generators/competing-consumers.md",
            "src/PatternKit.Generators/Messaging/CompetingConsumerGroupGenerator.cs",
            "test/PatternKit.Generators.Tests/CompetingConsumerGroupGeneratorTests.cs",
            null,
            "docs/examples/fulfillment-competing-consumers.md",
            "src/PatternKit.Examples/Messaging/FulfillmentCompetingConsumersExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/FulfillmentCompetingConsumersExampleTests.cs",
            ["fluent competing consumer group", "generated competing consumer builder", "DI-importable fulfillment worker example"]),

        Pattern("Pipes and Filters", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/pipes-and-filters.md",
            "src/PatternKit.Core/Messaging/PipesAndFilters/PipesAndFiltersPipeline.cs",
            "test/PatternKit.Tests/Messaging/PipesAndFilters/PipesAndFiltersPipelineTests.cs",
            "docs/generators/pipes-and-filters.md",
            "src/PatternKit.Generators/Messaging/PipesAndFiltersPipelineGenerator.cs",
            "test/PatternKit.Generators.Tests/PipesAndFiltersPipelineGeneratorTests.cs",
            null,
            "docs/examples/fulfillment-pipes-and-filters.md",
            "src/PatternKit.Examples/Messaging/FulfillmentPipesAndFiltersExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/FulfillmentPipesAndFiltersExampleTests.cs",
            ["fluent ordered pipeline", "generated pipeline builder", "DI-importable fulfillment workflow example"]),

        Pattern("Splitter", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-routing.md",
            "src/PatternKit.Core/Messaging/Routing/Splitter.cs",
            "test/PatternKit.Tests/Messaging/Routing/SplitterTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/SplitterAggregatorGenerator.cs",
            "test/PatternKit.Generators.Tests/SplitterAggregatorGeneratorTests.cs",
            null,
            "docs/examples/generated-splitter-aggregator.md",
            "src/PatternKit.Examples/Messaging/MessageRoutingExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/MessageRoutingExampleTests.cs",
            ["fluent splitter", "generated splitter", "DI-importable line-item message example"]),

        Pattern("Aggregator", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/message-routing.md",
            "src/PatternKit.Core/Messaging/Routing/Aggregator.cs",
            "test/PatternKit.Tests/Messaging/Routing/AggregatorTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/SplitterAggregatorGenerator.cs",
            "test/PatternKit.Generators.Tests/SplitterAggregatorGeneratorTests.cs",
            null,
            "docs/examples/generated-splitter-aggregator.md",
            "src/PatternKit.Examples/Messaging/MessageRoutingExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/MessageRoutingExampleTests.cs",
            ["fluent aggregator", "generated aggregator", "DI-importable correlated total example"]),

        Pattern("Routing Slip", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/routing-slip.md",
            "src/PatternKit.Core/Messaging/Routing/RoutingSlip.cs",
            "test/PatternKit.Tests/Messaging/Routing/RoutingSlipTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/RoutingSlipGenerator.cs",
            "test/PatternKit.Generators.Tests/RoutingSlipGeneratorTests.cs",
            null,
            "docs/examples/enterprise-messaging-workflows.md",
            "src/PatternKit.Examples/Messaging/RoutingSlipExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/RoutingSlipExampleTests.cs",
            ["fluent routing slip", "generated routing slip", "fulfillment itinerary example"]),

        Pattern("Saga / Process Manager", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/saga.md",
            "src/PatternKit.Core/Messaging/Sagas/Saga.cs",
            "test/PatternKit.Tests/Messaging/Sagas/SagaTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/SagaGenerator.cs",
            "test/PatternKit.Generators.Tests/SagaGeneratorTests.cs",
            null,
            "docs/examples/enterprise-messaging-workflows.md",
            "src/PatternKit.Examples/Messaging/SagaExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/SagaExampleTests.cs",
            ["fluent saga", "generated process manager", "order lifecycle example"]),

        Pattern("Mailbox", PatternFamily.EnterpriseIntegration,
            "docs/patterns/messaging/mailbox.md",
            "src/PatternKit.Core/Messaging/Mailboxes/Mailbox.cs",
            "test/PatternKit.Tests/Messaging/Mailboxes/MailboxTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/MailboxGenerator.cs",
            "test/PatternKit.Generators.Tests/MailboxGeneratorTests.cs",
            null,
            "docs/examples/generated-mailbox.md",
            "src/PatternKit.Examples/Messaging/MailboxExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/MailboxExampleTests.cs",
            ["fluent serialized inbox", "generated mailbox", "DI-importable bounded worker example"]),

        Pattern("Idempotent Receiver", PatternFamily.MessagingReliability,
            "docs/patterns/messaging/reliability.md",
            "src/PatternKit.Core/Messaging/Reliability/IdempotentReceiver.cs",
            "test/PatternKit.Tests/Messaging/Reliability/IdempotentReceiverTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/ReliabilityPipelineGenerator.cs",
            "test/PatternKit.Generators.Tests/ReliabilityPipelineGeneratorTests.cs",
            null,
            "docs/examples/generated-reliability-pipeline.md",
            "src/PatternKit.Examples/Messaging/ReliabilityExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/ReliabilityExampleTests.cs",
            ["runtime duplicate suppression", "generated reliability pipeline", "DI-importable at-least-once example"]),

        Pattern("Inbox", PatternFamily.MessagingReliability,
            "docs/patterns/messaging/reliability.md",
            "src/PatternKit.Core/Messaging/Reliability/InboxProcessor.cs",
            "test/PatternKit.Tests/Messaging/Reliability/IdempotentReceiverTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/ReliabilityPipelineGenerator.cs",
            "test/PatternKit.Generators.Tests/ReliabilityPipelineGeneratorTests.cs",
            null,
            "docs/examples/generated-reliability-pipeline.md",
            "src/PatternKit.Examples/Messaging/ReliabilityExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/ReliabilityExampleTests.cs",
            ["runtime inbox boundary", "generated inbox factory", "DI-importable reliable handoff example"]),

        Pattern("Outbox", PatternFamily.MessagingReliability,
            "docs/patterns/messaging/reliability.md",
            "src/PatternKit.Core/Messaging/Reliability/InMemoryOutbox.cs",
            "test/PatternKit.Tests/Messaging/Reliability/OutboxTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/ReliabilityPipelineGenerator.cs",
            "test/PatternKit.Generators.Tests/ReliabilityPipelineGeneratorTests.cs",
            null,
            "docs/examples/generated-reliability-pipeline.md",
            "src/PatternKit.Examples/Messaging/ReliabilityExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/ReliabilityExampleTests.cs",
            ["runtime outbox", "generated outbox factory", "DI-importable dispatch handoff example"]),

        Pattern("Request-Reply", PatternFamily.EnterpriseIntegration,
            "docs/examples/messaging-backplane-facade.md",
            "src/PatternKit.Examples/Messaging/BackplaneFacadeDemo.cs",
            "test/PatternKit.Examples.Tests/Messaging/BackplaneFacadeDemoTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/BackplaneTopologyGenerator.cs",
            "test/PatternKit.Generators.Tests/BackplaneTopologyGeneratorTests.cs",
            null,
            "docs/examples/messaging-backplane-facade.md",
            "src/PatternKit.Examples/Messaging/BackplaneFacadeDemo.cs",
            "test/PatternKit.Examples.Tests/Messaging/BackplaneFacadeDemoTests.cs",
            ["typed request/reply client", "generated backplane topology", "hosted backplane example"]),

        Pattern("Publish-Subscribe", PatternFamily.EnterpriseIntegration,
            "docs/examples/messaging-backplane-facade.md",
            "src/PatternKit.Examples/Messaging/BackplaneFacadeDemo.cs",
            "test/PatternKit.Examples.Tests/Messaging/BackplaneFacadeDemoTests.cs",
            "docs/generators/messaging.md",
            "src/PatternKit.Generators/Messaging/BackplaneTopologyGenerator.cs",
            "test/PatternKit.Generators.Tests/BackplaneTopologyGeneratorTests.cs",
            null,
            "docs/examples/messaging-backplane-facade.md",
            "src/PatternKit.Examples/Messaging/BackplaneFacadeDemo.cs",
            "test/PatternKit.Examples.Tests/Messaging/BackplaneFacadeDemoTests.cs",
            ["typed publish/subscribe", "generated backplane topology", "transport boundary example"]),

        Pattern("Retry", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/retry.md",
            "src/PatternKit.Core/Cloud/Retry/RetryPolicy.cs",
            "test/PatternKit.Tests/Cloud/Retry/RetryPolicyTests.cs",
            "docs/generators/retry.md",
            "src/PatternKit.Generators/Retry/RetryPolicyGenerator.cs",
            "test/PatternKit.Generators.Tests/RetryPolicyGeneratorTests.cs",
            null,
            "docs/examples/inventory-retry-policy.md",
            "src/PatternKit.Examples/RetryDemo/InventoryRetryDemo.cs",
            "test/PatternKit.Examples.Tests/RetryDemo/InventoryRetryDemoTests.cs",
            ["fluent retry policy", "generated retry policy", "DI-importable inventory lookup example"]),

        Pattern("Circuit Breaker", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/circuit-breaker.md",
            "src/PatternKit.Core/Cloud/CircuitBreaker/CircuitBreakerPolicy.cs",
            "test/PatternKit.Tests/Cloud/CircuitBreaker/CircuitBreakerPolicyTests.cs",
            "docs/generators/circuit-breaker.md",
            "src/PatternKit.Generators/CircuitBreaker/CircuitBreakerPolicyGenerator.cs",
            "test/PatternKit.Generators.Tests/CircuitBreakerPolicyGeneratorTests.cs",
            null,
            "docs/examples/fulfillment-circuit-breaker.md",
            "src/PatternKit.Examples/CircuitBreakerDemo/FulfillmentCircuitBreakerDemo.cs",
            "test/PatternKit.Examples.Tests/CircuitBreakerDemo/FulfillmentCircuitBreakerDemoTests.cs",
            ["fluent circuit breaker policy", "generated circuit breaker policy", "DI-importable fulfillment gateway example"]),

        Pattern("Bulkhead", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/bulkhead.md",
            "src/PatternKit.Core/Cloud/Bulkhead/BulkheadPolicy.cs",
            "test/PatternKit.Tests/Cloud/Bulkhead/BulkheadPolicyTests.cs",
            "docs/generators/bulkhead.md",
            "src/PatternKit.Generators/Bulkhead/BulkheadPolicyGenerator.cs",
            "test/PatternKit.Generators.Tests/BulkheadPolicyGeneratorTests.cs",
            null,
            "docs/examples/shipping-bulkhead.md",
            "src/PatternKit.Examples/BulkheadDemo/ShippingBulkheadDemo.cs",
            "test/PatternKit.Examples.Tests/BulkheadDemo/ShippingBulkheadDemoTests.cs",
            ["fluent bulkhead policy", "generated bulkhead policy", "DI-importable shipping allocation example"]),

        Pattern("Queue-Based Load Leveling", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/queue-load-leveling.md",
            "src/PatternKit.Core/Cloud/QueueLoadLeveling/QueueLoadLevelingPolicy.cs",
            "test/PatternKit.Tests/Cloud/QueueLoadLeveling/QueueLoadLevelingPolicyTests.cs",
            "docs/generators/queue-load-leveling.md",
            "src/PatternKit.Generators/QueueLoadLeveling/QueueLoadLevelingPolicyGenerator.cs",
            "test/PatternKit.Generators.Tests/QueueLoadLevelingPolicyGeneratorTests.cs",
            null,
            "docs/examples/fulfillment-queue-load-leveling.md",
            "src/PatternKit.Examples/QueueLoadLevelingDemo/FulfillmentQueueLoadLevelingDemo.cs",
            "test/PatternKit.Examples.Tests/QueueLoadLevelingDemo/FulfillmentQueueLoadLevelingDemoTests.cs",
            ["fluent bounded worker queue", "generated queue load leveling policy", "DI-importable fulfillment queue example"]),

        Pattern("Cache-Aside", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/cache-aside.md",
            "src/PatternKit.Core/Cloud/CacheAside/CacheAsidePolicy.cs",
            "test/PatternKit.Tests/Cloud/CacheAside/CacheAsidePolicyTests.cs",
            "docs/generators/cache-aside.md",
            "src/PatternKit.Generators/CacheAside/CacheAsidePolicyGenerator.cs",
            "test/PatternKit.Generators.Tests/CacheAsidePolicyGeneratorTests.cs",
            null,
            "docs/examples/product-catalog-cache-aside.md",
            "src/PatternKit.Examples/CacheAsideDemo/ProductCatalogCacheAsideDemo.cs",
            "test/PatternKit.Examples.Tests/CacheAsideDemo/ProductCatalogCacheAsideDemoTests.cs",
            ["fluent cache-aside policy", "generated cache-aside policy", "DI-importable product catalog read model example"]),

        Pattern("Rate Limiting", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/rate-limiting.md",
            "src/PatternKit.Core/Cloud/RateLimiting/RateLimitPolicy.cs",
            "test/PatternKit.Tests/Cloud/RateLimiting/RateLimitPolicyTests.cs",
            "docs/generators/rate-limiting.md",
            "src/PatternKit.Generators/RateLimiting/RateLimitPolicyGenerator.cs",
            "test/PatternKit.Generators.Tests/RateLimitPolicyGeneratorTests.cs",
            null,
            "docs/examples/product-search-rate-limiting.md",
            "src/PatternKit.Examples/RateLimitingDemo/ProductSearchRateLimitingDemo.cs",
            "test/PatternKit.Examples.Tests/RateLimitingDemo/ProductSearchRateLimitingDemoTests.cs",
            ["fluent rate-limit policy", "generated rate-limit policy", "DI-importable tenant product search example"]),

        Pattern("External Configuration Store", PatternFamily.CloudArchitecture,
            "docs/patterns/cloud/external-configuration-store.md",
            "src/PatternKit.Core/Cloud/ExternalConfigurationStore/ExternalConfigurationStore.cs",
            "test/PatternKit.Tests/Cloud/ExternalConfigurationStore/ExternalConfigurationStoreTests.cs",
            "docs/generators/external-configuration-store.md",
            "src/PatternKit.Generators/Cloud/ExternalConfigurationStoreGenerator.cs",
            "test/PatternKit.Generators.Tests/ExternalConfigurationStoreGeneratorTests.cs",
            null,
            "docs/examples/tenant-external-configuration-store.md",
            "src/PatternKit.Examples/ExternalConfigurationStoreDemo/TenantExternalConfigurationStoreDemo.cs",
            "test/PatternKit.Examples.Tests/ExternalConfigurationStoreDemo/TenantExternalConfigurationStoreDemoTests.cs",
            ["fluent external configuration store", "generated external configuration store", "DI-importable tenant settings example"]),

        Pattern("CQRS", PatternFamily.ApplicationArchitecture,
            "docs/generators/dispatcher.md",
            "src/PatternKit.Core/Behavioral/Mediator/Mediator.cs",
            "test/PatternKit.Tests/Behavioral/Mediator/MediatorTests.cs",
            "docs/generators/dispatcher.md",
            "src/PatternKit.Generators/Messaging/DispatcherGenerator.cs",
            "test/PatternKit.Generators.Tests/DispatcherGeneratorTests.cs",
            null,
            "docs/examples/cqrs-dispatcher.md",
            "src/PatternKit.Examples/Messaging/CqrsPatternExample.cs",
            "test/PatternKit.Examples.Tests/Messaging/CqrsPatternExampleTests.cs",
            ["fluent mediator command/query separation", "generated dispatcher", "DI-importable CQRS example"]),
        Pattern("Specification", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/specification.md",
            "src/PatternKit.Core/Application/Specification/Specification.cs",
            "test/PatternKit.Tests/Application/Specification/SpecificationTests.cs",
            "docs/generators/specification.md",
            "src/PatternKit.Generators/Specification/SpecificationGenerator.cs",
            "test/PatternKit.Generators.Tests/SpecificationGeneratorTests.cs",
            null,
            "docs/examples/loan-approval-specifications.md",
            "src/PatternKit.Examples/SpecificationDemo/LoanApprovalSpecificationDemo.cs",
            "test/PatternKit.Examples.Tests/SpecificationDemo/LoanApprovalSpecificationDemoTests.cs",
            ["fluent specification composition", "generated specification registry", "DI-importable loan approval example"]),

        Pattern("Repository", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/repository.md",
            "src/PatternKit.Core/Application/Repository/Repository.cs",
            "test/PatternKit.Tests/Application/Repository/RepositoryTests.cs",
            "docs/generators/repository.md",
            "src/PatternKit.Generators/Repository/RepositoryGenerator.cs",
            "test/PatternKit.Generators.Tests/RepositoryGeneratorTests.cs",
            null,
            "docs/examples/order-repository-pattern.md",
            "src/PatternKit.Examples/RepositoryDemo/OrderRepositoryDemo.cs",
            "test/PatternKit.Examples.Tests/RepositoryDemo/OrderRepositoryDemoTests.cs",
            ["fluent async repository", "generated repository factory", "DI-importable order persistence example"]),

        Pattern("Unit of Work", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/unit-of-work.md",
            "src/PatternKit.Core/Application/UnitOfWork/UnitOfWork.cs",
            "test/PatternKit.Tests/Application/UnitOfWork/UnitOfWorkTests.cs",
            "docs/generators/unit-of-work.md",
            "src/PatternKit.Generators/UnitOfWork/UnitOfWorkGenerator.cs",
            "test/PatternKit.Generators.Tests/UnitOfWorkGeneratorTests.cs",
            null,
            "docs/examples/checkout-unit-of-work-pattern.md",
            "src/PatternKit.Examples/UnitOfWorkDemo/CheckoutUnitOfWorkDemo.cs",
            "test/PatternKit.Examples.Tests/UnitOfWorkDemo/CheckoutUnitOfWorkDemoTests.cs",
            ["fluent commit boundary", "generated unit-of-work factory", "DI-importable checkout example"]),

        Pattern("Data Mapper", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/data-mapper.md",
            "src/PatternKit.Core/Application/DataMapping/DataMapper.cs",
            "test/PatternKit.Tests/Application/DataMapping/DataMapperTests.cs",
            "docs/generators/data-mapper.md",
            "src/PatternKit.Generators/DataMapping/DataMapperGenerator.cs",
            "test/PatternKit.Generators.Tests/DataMapperGeneratorTests.cs",
            null,
            "docs/examples/order-data-mapper-pattern.md",
            "src/PatternKit.Examples/DataMapperDemo/OrderDataMapperDemo.cs",
            "test/PatternKit.Examples.Tests/DataMapperDemo/OrderDataMapperDemoTests.cs",
            ["fluent domain/data mapper", "generated mapper factory", "DI-importable order persistence example"]),

        Pattern("Identity Map", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/identity-map.md",
            "src/PatternKit.Core/Application/IdentityMap/IdentityMap.cs",
            "test/PatternKit.Tests/Application/IdentityMap/IdentityMapTests.cs",
            "docs/generators/identity-map.md",
            "src/PatternKit.Generators/IdentityMap/IdentityMapGenerator.cs",
            "test/PatternKit.Generators.Tests/IdentityMapGeneratorTests.cs",
            null,
            "docs/examples/order-identity-map-pattern.md",
            "src/PatternKit.Examples/IdentityMapDemo/OrderIdentityMapDemo.cs",
            "test/PatternKit.Examples.Tests/IdentityMapDemo/OrderIdentityMapDemoTests.cs",
            ["fluent scoped identity map", "generated identity-map factory", "DI-importable request scope example"]),

        Pattern("Transaction Script", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/transaction-script.md",
            "src/PatternKit.Core/Application/TransactionScript/TransactionScript.cs",
            "test/PatternKit.Tests/Application/TransactionScript/TransactionScriptTests.cs",
            "docs/generators/transaction-script.md",
            "src/PatternKit.Generators/TransactionScript/TransactionScriptGenerator.cs",
            "test/PatternKit.Generators.Tests/TransactionScriptGeneratorTests.cs",
            null,
            "docs/examples/order-transaction-script-pattern.md",
            "src/PatternKit.Examples/TransactionScriptDemo/OrderTransactionScriptDemo.cs",
            "test/PatternKit.Examples.Tests/TransactionScriptDemo/OrderTransactionScriptDemoTests.cs",
            ["fluent application workflow", "generated script factory", "DI-importable service operation"]),

        Pattern("Service Layer", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/service-layer.md",
            "src/PatternKit.Core/Application/ServiceLayer/ServiceLayer.cs",
            "test/PatternKit.Tests/Application/ServiceLayer/ServiceLayerTests.cs",
            "docs/generators/service-layer.md",
            "src/PatternKit.Generators/ServiceLayer/ServiceLayerOperationGenerator.cs",
            "test/PatternKit.Generators.Tests/ServiceLayerGeneratorTests.cs",
            null,
            "docs/examples/customer-service-layer-pattern.md",
            "src/PatternKit.Examples/ServiceLayerDemo/CustomerServiceLayerDemo.cs",
            "test/PatternKit.Examples.Tests/ServiceLayerDemo/CustomerServiceLayerDemoTests.cs",
            ["fluent application service boundary", "generated operation factory", "DI-importable workflow"]),

        Pattern("Domain Event", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/domain-event.md",
            "src/PatternKit.Core/Application/DomainEvents/DomainEventDispatcher.cs",
            "test/PatternKit.Tests/Application/DomainEvents/DomainEventDispatcherTests.cs",
            "docs/generators/domain-event.md",
            "src/PatternKit.Generators/DomainEvents/DomainEventDispatcherGenerator.cs",
            "test/PatternKit.Generators.Tests/DomainEventDispatcherGeneratorTests.cs",
            null,
            "docs/examples/order-domain-event-pattern.md",
            "src/PatternKit.Examples/DomainEventDemo/OrderDomainEventDemo.cs",
            "test/PatternKit.Examples.Tests/DomainEventDemo/OrderDomainEventDemoTests.cs",
            ["fluent domain event dispatcher", "generated handler registry", "DI-importable projection and audit workflow"]),

        Pattern("Table Data Gateway", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/table-data-gateway.md",
            "src/PatternKit.Core/Application/TableDataGateway/TableDataGateway.cs",
            "test/PatternKit.Tests/Application/TableDataGateway/TableDataGatewayTests.cs",
            "docs/generators/table-data-gateway.md",
            "src/PatternKit.Generators/TableDataGateway/TableDataGatewayGenerator.cs",
            "test/PatternKit.Generators.Tests/TableDataGatewayGeneratorTests.cs",
            null,
            "docs/examples/order-table-data-gateway-pattern.md",
            "src/PatternKit.Examples/TableDataGatewayDemo/OrderTableDataGatewayDemo.cs",
            "test/PatternKit.Examples.Tests/TableDataGatewayDemo/OrderTableDataGatewayDemoTests.cs",
            ["fluent row gateway", "generated table gateway factory", "DI-importable row workflow"]),

        Pattern("Event Sourcing", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/event-sourcing.md",
            "src/PatternKit.Core/Application/EventSourcing/EventStore.cs",
            "test/PatternKit.Tests/Application/EventSourcing/EventStoreTests.cs",
            "docs/generators/event-sourcing.md",
            "src/PatternKit.Generators/EventSourcing/EventStoreGenerator.cs",
            "test/PatternKit.Generators.Tests/EventStoreGeneratorTests.cs",
            null,
            "docs/examples/order-event-sourcing-pattern.md",
            "src/PatternKit.Examples/EventSourcingDemo/OrderEventSourcingDemo.cs",
            "test/PatternKit.Examples.Tests/EventSourcingDemo/OrderEventSourcingDemoTests.cs",
            ["fluent append-only event store", "generated event store factory", "DI-importable replay workflow"]),

        Pattern("Feature Toggle", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/feature-toggle.md",
            "src/PatternKit.Core/Application/FeatureToggles/FeatureToggleSet.cs",
            "test/PatternKit.Tests/Application/FeatureToggles/FeatureToggleSetTests.cs",
            "docs/generators/feature-toggle.md",
            "src/PatternKit.Generators/FeatureToggles/FeatureToggleSetGenerator.cs",
            "test/PatternKit.Generators.Tests/FeatureToggleSetGeneratorTests.cs",
            null,
            "docs/examples/checkout-feature-toggle-pattern.md",
            "src/PatternKit.Examples/FeatureToggleDemo/CheckoutFeatureToggleDemo.cs",
            "test/PatternKit.Examples.Tests/FeatureToggleDemo/CheckoutFeatureToggleDemoTests.cs",
            ["fluent contextual toggles", "generated toggle set factory", "DI-importable rollout workflow"]),

        Pattern("Audit Log", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/audit-log.md",
            "src/PatternKit.Core/Application/AuditLog/AuditLog.cs",
            "test/PatternKit.Tests/Application/AuditLog/AuditLogTests.cs",
            "docs/generators/audit-log.md",
            "src/PatternKit.Generators/AuditLog/AuditLogGenerator.cs",
            "test/PatternKit.Generators.Tests/AuditLogGeneratorTests.cs",
            null,
            "docs/examples/order-audit-log-pattern.md",
            "src/PatternKit.Examples/AuditLogDemo/OrderAuditLogDemo.cs",
            "test/PatternKit.Examples.Tests/AuditLogDemo/OrderAuditLogDemoTests.cs",
            ["fluent append-only audit trail", "generated audit log factory", "DI-importable order audit workflow"]),

        Pattern("Materialized View", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/materialized-view.md",
            "src/PatternKit.Core/Application/MaterializedViews/MaterializedView.cs",
            "test/PatternKit.Tests/Application/MaterializedViews/MaterializedViewTests.cs",
            "docs/generators/materialized-view.md",
            "src/PatternKit.Generators/MaterializedViews/MaterializedViewGenerator.cs",
            "test/PatternKit.Generators.Tests/MaterializedViewGeneratorTests.cs",
            null,
            "docs/examples/order-materialized-view-pattern.md",
            "src/PatternKit.Examples/MaterializedViewDemo/OrderMaterializedViewDemo.cs",
            "test/PatternKit.Examples.Tests/MaterializedViewDemo/OrderMaterializedViewDemoTests.cs",
            ["fluent event projection", "generated projection factory", "DI-importable read-model workflow"]),

        Pattern("Anti-Corruption Layer", PatternFamily.ApplicationArchitecture,
            "docs/patterns/application/anti-corruption-layer.md",
            "src/PatternKit.Core/Application/AntiCorruption/AntiCorruptionLayer.cs",
            "test/PatternKit.Tests/Application/AntiCorruption/AntiCorruptionLayerTests.cs",
            "docs/generators/anti-corruption-layer.md",
            "src/PatternKit.Generators/AntiCorruption/AntiCorruptionLayerGenerator.cs",
            "test/PatternKit.Generators.Tests/AntiCorruptionLayerGeneratorTests.cs",
            null,
            "docs/examples/legacy-order-anti-corruption-layer.md",
            "src/PatternKit.Examples/AntiCorruptionDemo/LegacyOrderAntiCorruptionDemo.cs",
            "test/PatternKit.Examples.Tests/AntiCorruptionDemo/LegacyOrderAntiCorruptionDemoTests.cs",
            ["fluent translation boundary", "generated anti-corruption layer", "DI-importable legacy order import example"])
    ];

    public IReadOnlyList<PatternCoverageDescriptor> Patterns => Items;

    private static PatternCoverageDescriptor Pattern(
        string name,
        PatternFamily family,
        string fluentDocumentationPath,
        string fluentSourcePath,
        string fluentTestPath,
        string? generatorDocumentationPath,
        string? generatorSourcePath,
        string? generatorTestPath,
        string? trackingIssueUrl,
        string exampleDocumentationPath,
        string exampleSourcePath,
        string exampleTestPath,
        IReadOnlyList<string> integrationNotes)
        => new(
            name,
            family,
            new PatternImplementationPath(
                name,
                fluentDocumentationPath,
                fluentSourcePath,
                fluentTestPath,
                generatorDocumentationPath,
                generatorSourcePath,
                generatorTestPath,
                trackingIssueUrl,
                exampleDocumentationPath,
                exampleSourcePath,
                exampleTestPath),
            integrationNotes);
}

public static class PatternKitPatternCatalogServiceCollectionExtensions
{
    public static IServiceCollection AddPatternKitPatternCatalog(this IServiceCollection services)
    {
        services.AddSingleton<IPatternKitPatternCatalog, PatternKitPatternCatalog>();
        return services;
    }
}
