using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace PatternKit.Generators.QueueLoadLeveling;

[Generator]
public sealed class QueueLoadLevelingPolicyGenerator : IIncrementalGenerator
{
    private const string AttributeName = "PatternKit.Generators.QueueLoadLeveling.GenerateQueueLoadLevelingPolicyAttribute";

    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKQL001", "Queue Load Leveling policy host must be partial",
        "Type '{0}' is marked with [GenerateQueueLoadLevelingPolicy] but is not declared as partial",
        "PatternKit.Generators.QueueLoadLeveling", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor InvalidConfiguration = new(
        "PKQL002", "Queue Load Leveling policy configuration is invalid",
        "Queue Load Leveling policy '{0}' must have MaxConcurrentWorkers >= 1, MaxQueueLength >= 0, and QueueTimeoutMilliseconds >= 0",
        "PatternKit.Generators.QueueLoadLeveling", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == AttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var resultType = attribute.ConstructorArguments.Length >= 1 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        if (resultType is null)
            return;

        var maxConcurrentWorkers = GetNamedInt(attribute, "MaxConcurrentWorkers") ?? 1;
        var maxQueueLength = GetNamedInt(attribute, "MaxQueueLength") ?? 100;
        var queueTimeoutMilliseconds = GetNamedInt(attribute, "QueueTimeoutMilliseconds") ?? 30000;
        if (maxConcurrentWorkers < 1 || maxQueueLength < 0 || queueTimeoutMilliseconds < 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidConfiguration, node.Identifier.GetLocation(), type.Name));
            return;
        }

        context.AddSource($"{type.Name}.QueueLoadLevelingPolicy.g.cs", SourceText.From(
            GenerateSource(
                type,
                resultType,
                GetNamedString(attribute, "FactoryMethodName") ?? "Create",
                GetNamedString(attribute, "PolicyName") ?? "queue-load-leveling",
                maxConcurrentWorkers,
                maxQueueLength,
                queueTimeoutMilliseconds),
            Encoding.UTF8));
    }

    private static string GenerateSource(
        INamedTypeSymbol type,
        INamedTypeSymbol resultType,
        string factoryMethodName,
        string policyName,
        int maxConcurrentWorkers,
        int maxQueueLength,
        int queueTimeoutMilliseconds)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var resultTypeName = resultType.ToDisplayString(TypeFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(GetAccessibility(type.DeclaredAccessibility)).Append(' ');
        if (type.IsStatic)
            sb.Append("static ");
        else if (type.IsAbstract && type.TypeKind == TypeKind.Class)
            sb.Append("abstract ");
        else if (type.IsSealed && type.TypeKind == TypeKind.Class)
            sb.Append("sealed ");
        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Cloud.QueueLoadLeveling.QueueLoadLevelingPolicy<").Append(resultTypeName).Append("> ").Append(factoryMethodName).AppendLine("()");
        sb.AppendLine("    {");
        sb.Append("        return global::PatternKit.Cloud.QueueLoadLeveling.QueueLoadLevelingPolicy<").Append(resultTypeName).Append(">.Create(\"").Append(Escape(policyName)).AppendLine("\")");
        sb.Append("            .WithMaxConcurrentWorkers(").Append(maxConcurrentWorkers).AppendLine(")");
        sb.Append("            .WithMaxQueueLength(").Append(maxQueueLength).AppendLine(")");
        sb.Append("            .WithQueueTimeout(global::System.TimeSpan.FromMilliseconds(").Append(queueTimeoutMilliseconds).AppendLine("))");
        sb.AppendLine("            .Build();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static int? GetNamedInt(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as int?;

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };
}
