using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PatternKit.Generators.EventSourcing;

[Generator]
public sealed class EventStoreGenerator : IIncrementalGenerator
{
    private const string GenerateAttributeName = "PatternKit.Generators.EventSourcing.GenerateEventStoreAttribute";

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "PKES001", "Event Store host must be partial",
        "Type '{0}' is marked with [GenerateEventStore] but is not declared as partial",
        "PatternKit.Generators.EventSourcing", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateAttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (Type: (INamedTypeSymbol)ctx.TargetSymbol, Node: (TypeDeclarationSyntax)ctx.TargetNode, Attributes: ctx.Attributes));

        context.RegisterSourceOutput(candidates, static (spc, candidate) =>
        {
            var attr = candidate.Attributes.FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == GenerateAttributeName);
            if (attr is not null)
                Generate(spc, candidate.Type, candidate.Node, attr);
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type, TypeDeclarationSyntax node, AttributeData attribute)
    {
        if (!node.Modifiers.Any(static modifier => modifier.Text == "partial"))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.Identifier.GetLocation(), type.Name));
            return;
        }

        var eventType = attribute.ConstructorArguments.Length > 0 ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol : null;
        var streamIdType = attribute.ConstructorArguments.Length > 1 ? attribute.ConstructorArguments[1].Value as INamedTypeSymbol : null;
        if (eventType is null || streamIdType is null)
            return;

        var storeName = GetNamedString(attribute, "StoreName");
        if (string.IsNullOrWhiteSpace(storeName))
            storeName = type.Name;

        context.AddSource($"{type.Name}.EventStore.g.cs", SourceText.From(
            GenerateSource(type, eventType, streamIdType, GetNamedString(attribute, "FactoryName") ?? "Create", storeName!),
            Encoding.UTF8));
    }

    private static string GenerateSource(INamedTypeSymbol type, INamedTypeSymbol eventType, INamedTypeSymbol streamIdType, string factoryName, string storeName)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var eventName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var streamIdName = streamIdType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(GetAccessibility(type.DeclaredAccessibility)).Append(' ');
        if (type.IsStatic)
            sb.Append("static ");
        else if (type.IsAbstract && type.TypeKind == TypeKind.Class)
            sb.Append("abstract ");
        else if (type.IsSealed && type.TypeKind == TypeKind.Class)
            sb.Append("sealed ");
        sb.Append("partial ").Append(type.TypeKind == TypeKind.Struct ? "struct" : "class").Append(' ').Append(type.Name).AppendLine();
        sb.AppendLine("{");
        sb.Append("    public static global::PatternKit.Application.EventSourcing.InMemoryEventStore<")
            .Append(eventName).Append(", ").Append(streamIdName).Append("> ").Append(factoryName).AppendLine("()");
        sb.Append("        => global::PatternKit.Application.EventSourcing.InMemoryEventStore<")
            .Append(eventName).Append(", ").Append(streamIdName).Append(">.Create(\"").Append(Escape(storeName)).AppendLine("\").Build();");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string? GetNamedString(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(kv => kv.Key == name).Value.Value as string;

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };
}
