using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PatternKit.Generators.Command;

[Generator]
public sealed class CommandGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                              SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly DiagnosticDescriptor MustBePartial = new("PKCMD001", "Command type must be partial", "Type '{0}' is marked with [Command] but is not declared as partial", "PatternKit.Generators.Command", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingHandler = new("PKCMD002", "Command handler missing", "No [CommandHandler] method found for command type '{0}'", "PatternKit.Generators.Command", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MultipleHandlers = new("PKCMD003", "Multiple command handlers", "Multiple [CommandHandler] methods found for command type '{0}'", "PatternKit.Generators.Command", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidHandler = new("PKCMD004", "Command handler signature invalid", "Handler method '{0}' must accept the command as its first parameter and return void or ValueTask", "PatternKit.Generators.Command", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PatternKit.Generators.Command.CommandAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => ctx).Collect();

        context.RegisterSourceOutput(context.CompilationProvider.Combine(commands), static (spc, pair) =>
        {
            var compilation = pair.Left;
            foreach (var ctx in pair.Right)
            {
                if (ctx.TargetSymbol is INamedTypeSymbol command)
                {
                    var attr = ctx.Attributes.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Command.CommandAttribute");
                    if (attr is not null) Generate(spc, compilation, command, attr, ctx.TargetNode);
                }
            }
        });
    }

    private static void Generate(SourceProductionContext context, Compilation compilation, INamedTypeSymbol command, AttributeData attr, SyntaxNode node)
    {
        if (!IsPartial(node))
        {
            context.ReportDiagnostic(Diagnostic.Create(MustBePartial, node.GetLocation(), command.Name));
            return;
        }

        var handlers = GetAllTypes(compilation.GlobalNamespace)
            .SelectMany(t => t.GetMembers().OfType<IMethodSymbol>())
            .Where(m => m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "PatternKit.Generators.Command.CommandHandlerAttribute"))
            .Where(m => m.Parameters.Length > 0 && SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, command))
            .ToArray();

        if (handlers.Length == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingHandler, node.GetLocation(), command.Name));
            return;
        }
        if (handlers.Length > 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MultipleHandlers, node.GetLocation(), command.Name));
            return;
        }

        var handler = handlers[0];
        if (!IsValidHandler(handler))
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidHandler, node.GetLocation(), handler.Name));
            return;
        }

        var adapterName = GetString(attr, nameof(CommandAttribute.CommandTypeName), command.Name + "Command");
        context.AddSource($"{command.Name}.Command.g.cs", Render(command, handler, adapterName));
    }

    private static string Render(INamedTypeSymbol command, IMethodSymbol handler, string adapterName)
    {
        var ns = command.ContainingNamespace.IsGlobalNamespace ? null : command.ContainingNamespace.ToDisplayString();
        var commandType = command.ToDisplayString(TypeFormat);
        var handlerType = handler.ContainingType.ToDisplayString(TypeFormat);
        var isAsync = handler.ReturnType.ToDisplayString() == "System.Threading.Tasks.ValueTask";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append("public readonly partial struct ").Append(adapterName).AppendLine();
        sb.AppendLine("{");
        if (isAsync)
        {
            sb.Append("    public static global::System.Threading.Tasks.ValueTask ExecuteAsync(").Append(handlerType).Append(" handler, ").Append(commandType).Append(" command, global::System.Threading.CancellationToken ct = default)").AppendLine();
            sb.Append("        => handler.").Append(handler.Name).Append("(command");
            if (handler.Parameters.Length > 1) sb.Append(", ct");
            sb.AppendLine(");");
        }
        else
        {
            sb.Append("    public static void Execute(").Append(handlerType).Append(" handler, in ").Append(commandType).Append(" command)").AppendLine();
            sb.Append("        => handler.").Append(handler.Name).Append('(').Append(handler.Parameters[0].RefKind == RefKind.In ? "in command" : "command").AppendLine(");");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsValidHandler(IMethodSymbol method)
    {
        if (method.Parameters.Length is < 1 or > 2) return false;
        if (method.Parameters.Length == 2 && method.Parameters[1].Type.ToDisplayString() != "System.Threading.CancellationToken") return false;
        return method.ReturnsVoid || method.ReturnType.ToDisplayString() == "System.Threading.Tasks.ValueTask";
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in GetNestedTypes(type)) yield return nested;
        }
        foreach (var child in ns.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(child)) yield return type;
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var child in GetNestedTypes(nested)) yield return child;
        }
    }

    private static bool IsPartial(SyntaxNode node) => node is TypeDeclarationSyntax type && type.Modifiers.Any(SyntaxKind.PartialKeyword);
    private static string GetString(AttributeData attr, string name, string fallback) => attr.NamedArguments.FirstOrDefault(a => a.Key == name).Value.Value as string ?? fallback;
}
